### ISSUE TITLE
PESTPP-SEN issue in the manual

### ISSUE THREAD

**Issue by mnfienen-usgs** [usgs/pestpp#10]
Currently, the documentation indicates that control of the global sensitivity process in `pestpp-sen` is through the use of "++" arguments. However, the code still requires an external `.gsa` file at the moment.

**Comment by jwhite-usgs** [comment]
Thanks for the heads up, @mnfienen-usgs .  This has been changed on `develop`:  PESTPP-SEN now use ++ args only (no .gsa file) - the documentation has also be updated.
