### ISSUE TITLE
Uniform upgrade vectors across lambdas when using JTQJ matrix inversion in PESTPP-GLM

### ISSUE THREAD

**Issue by ckikuchi** [usgs/pestpp#100]
Hello,

I have a question about calculation of the parameter upgrade vectors. I have used PEST++ for calibrating two models recently (using the default jtqj option) for which I found that the computed upgrade vectors were uniform across the default lambda values. 

In both cases, I also tested using an older release of PEST++ that still included the ++mat_inv(Q1/2Z) option, and using this alternate formulation the upgrade vectors did vary across the different lambdas. I have two questions:

1. Is there a reason why this behavior should differ across the two matrix inversion options? 
2. Has this issue been reported (for example outside GitHub) or has this been observed in the past?

Thank you!
-Colin

**Comment by jtwhite79** [comment]
Those are some tough questions!  There is a lot code and complexity around handling the upgrade calculations in pestpp-glm, mostly around dealing with parameters at bounds and/or going out of bounds, as well as enforcing parameter change limits.   In your two cases, were there parameters being frozen during the upgrade calcs for these reasons (should be reported in the log or rec file)?

Im not an expert on this stuff, but my understanding is that the JtQJ ("normal") formulation is better conditioned compared to the Q1/2J formulation.  PESTPP-GLM now has a few options for "normal form", which deals with how to scale JtQJ with lambda.  Have you experimented with these different forms at all?  

I'll add a trap for identical upgrade vectors in the next release so at least we dont waste runs/time...
