### ISSUE TITLE
pestpp5.0.8.docx is corrupted - pestpp5.0.7.docx is fine

### ISSUE THREAD

**Issue by timcera** [usgs/pestpp#105]
pestpp5.0.8.docx is corrupted.  I was able to download and read pestpp5.0.7.docx without and problems.

**Comment by jtwhite79** [comment]
That is a bummer.  I can open it on mac and windows - not sure whats going on (word...) - does word just say its corrupt and it cant open it? I added a pdf of 5.0.8 to the documentation folder on the master branch to help.

**Comment by wkitlasten** [comment]
fwiw, it opens on my windows 10 machine with LibreOffice Writer.

**Comment by timcera** [comment]
Apologies.  Don't know what happened before but it works now.
