### ISSUE TITLE
Feature request: ins read error trap during worker batch runs

### ISSUE THREAD

**Issue by cnicol-gwlogic** [usgs/pestpp#107]
Hi Jeremy,

This is one to consider for trapping dumb moves like mine: 

I have (or had) a pestpp case where a model output file being read via an instruction file fails on some worker runs. I think it is ultimately caused by an overflow in the model code (mfusg sfr2) in certain rare situations) - but, ignoring that for now: could we add a trap for ins file reads sometimes failing during batch pestpp runs? The reason I suggest this is that I found this hard to work out what was happening, even when re-running the failed worker over the same model output files.

A few other details:
- My case was with the IES (5.0.0 git release sept 1 2020), but it is repeatable with GLM, and probably the other executables). 
- In my case pestpp was dying with an unhandled exception window popping up on some machines, and just silently dying on others (windows 10 latest - the diff probably because I have c++/VS installed on some worker PCs and not others). 
- This always happened at the part printed to the worker console as "processing instruction files with {n} threads...thread {m} processed 1 instruction files". 
- When this happened the manager would report "...receive failed from agent..." and "...closed connection to agent..." to the rmr file. So I knew where the problem was, but not what it was, which was hard to work out (for me at least).

I'd be happy to have a stab at this feature if you are interested.

Thanks,
Chris.

**Comment by jtwhite79** [comment]
I understand this pain having also encountered this issue!  It was a result of moving to multithreaded tpl and ins processing and not properly trapping exceptions raised by the threads.  Ive done some testing and I'm hoping it has been fixed as of 5.0.8 
(https://github.com/usgs/pestpp/commit/a5fa88f1c21c04a0f84711b581e32f3a5941d1dd ). It should be trapping the ins and or tpl error message and sending it back to the master rmr file.  Let us know if the issue has not been fixed for you and I'll dig in.  

There is also a freeze-on-fail flag that can used to keep workers where a run has failed from continuing or exiting - ive found this pretty useful for chasing ghosts!

**Comment by cnicol-gwlogic** [comment]
Too easy! Thanks a lot for the info - awesome. I didn't realise I did not have the latest and greatest exes - I have  grabbed those, and will try again / report back / open a new issue if any residual issues. This might actually fix another little issue I was having with threading actually (on the master) - again, will report back if need be. Cheers.
