### ISSUE TITLE
overwriting the global pe instance

### ISSUE THREAD

**Issue by jtwhite79** [usgs/pestpp#108]
https://github.com/usgs/pestpp/blob/4446383c1a793e6ae0b4f2b2e2b6aff7299f44f4/src/programs/pestpp-da/pestpp-da.cpp#L481

@aymanalz - Im not sure about this line.  I think it overwrites the global pe, right?  What's your thinking on this - what am I missing?

**Comment by aymanalz** [comment]
You are right! . Instead the following is used.
cycle_curr_pe =  da.get_pe();

**Comment by jtwhite79** [comment]
Sweet.  Thanks @aymanalz
