### ISSUE TITLE
pestpp-da "dry run"

### ISSUE THREAD

**Issue by jtwhite79** [usgs/pestpp#110]
@aymanalz - I was thinking it might be helpful to have a "dry run" option for pestpp-da where run thru the cycles, get the child pest object and make sure the pars and obs are in sync with the templates and instructions (no model calls).  For me, this has been to mess and hard to detect until you are already into the run.  thoughts?

**Comment by aymanalz** [comment]
I added some code to forward run the model throughout all time cycles using the initial parameter (and/or initial dynamic states) in the control file. This option is activated when noptmax = 0 and can be used to check if the model datasets and PEST dataset are correctly setup.

**Comment by jtwhite79** [comment]
Thanks @aymanalz .  I thought it was already doing the noptmax 0 thing...what I was talking about was just forming the child pest object and making sure the pars and obs in each child pest were compatible with the template and instruction files.  So really just a checker function.
