### ISSUE TITLE
'Pass-through' of Ensemble Member Number to Agent PC.

### ISSUE THREAD

**Issue by jrwbell** [usgs/pestpp#120]
Hi.

I'm a novice user of PESTPP-IES and I'm thinking through a problem I'd like to try and solve.

What I would like to do is to generate 300 realisations of a property field, stochastically, and then use Pilot Points to 'warp' each of their respective fields during calibration.

If I start with an ensemble of 300 members, I would like each member to use its own, initial property field and then, during calibration, that particular members' Pilot Points values 'calibrates' its initial own property field. i.e. Pilot Points Kh and Kz etc are used as scaling factors to the stochastically generated property field pertaining to that member.

The above is not particular different to the PEST tutorial where PESTPP-IES is deployed, except that the Pilot Points will be 'warping' the original field, rather than rendering the field directly.

Anyhow, the bit that I am stuck on is that I don't know a way to transmit the ensemble member number through the "* model command / pestgv.bat file" structure.

To explain, I intend to have the 300 realisations of property fields on all of the PEST Agent PCs.  As PESTPP-IES progresses, I just need to pass through the "Ensemble Member Number" being tested on a particular Agent PC, so that I could add something like the following, prior to the PLPROC steps:

COPY /Y CurrentPropertyField.dat.%%i CurrentPropertyField.dat
where %%i is the Ensemble Member Number.

I would appreciate it if someone is aware of how this might be able to be done.

regards
Justin

**Comment by cnicol-gwlogic** [comment]
Hi @jrwbell - You can get this info from the 1st line of run.info, which is written in each worker's folder (for each run). It's a bit messy to do in a batch file, but is doable using tokens and delimiters (eg https://stackoverflow.com/questions/130116/windows-batch-commands-to-read-first-line-from-text-file - I think you could call the accepted answer's batch with "1 ," to get run id - but test this to check I've got that right).  It would be easier / cleaner to do with say a small python script called from the model batch file - and you could extract/copy your stochastic files from there too maybe.
Chris.

**Comment by jtwhite79** [comment]
@cnicol-gwlogic is right on it.  just wanted to add that the first line of run.info is the index of the realization (not the actual realization name).

On the `feat_newtools` branch, the actual realization name is getting written to the third line of run.info (and its tagged as "realization=" - this issue has come up several times).  Lemme know if you are interested in this newer functionality and I can get you an exe.  Also, some people have added a "fixed" parameter to the control file and assigned it the value of the realization name in an external parameter ensemble (assuming the names can be represented as numeric) - then this value gets written to a file in the worker directory of your choosing (thru the template you setup for this "realization" parameter).

**Comment by jrwbell** [comment]
Thank you.
