### ISSUE TITLE
issue restarting PEST-IES from parameter and observation ensembles generated by PEST-IES

### ISSUE THREAD

**Issue by RyanConway91** [usgs/pestpp#121]
Hello,
I am trying to restart a PEST-IES run using the results of a previous run. Here are my IES options:
++ ies_num_reals(48)
++ ies_lambda_mults(0.1,1.0,5.0,10.0)
++ lambda_scale_fac(0.75, 1.0, 1.1)
++ ies_subset_size(4)
++ overdue_giveup_minutes(150)
++ overdue_giveup_fac(40)
++ ies_csv_by_reals(false)
++ ies_observation_ensemble(cal1_ps.obs+noise.csv)
++ ies_parameter_ensemble(cal1_ps.0.par.csv)
++ ies_restart_observation_ensemble(cal1_ps.19.obs.csv)
++ ies_restart_parameter_ensemble(cal1_ps.19.par.csv)

All the csv files being passes are generated by PEST-IES on a previous run
When I start PEST-IES, get the following error:
Ensemble Error: Ensemble:: get_real_vector() : ireal (47)>= real.shape[0] (47)
![image](https://user-images.githubusercontent.com/25184697/108938101-1134dd00-7615-11eb-8875-c88bfd2b70b1.png)

**Comment by jtwhite79** [comment]
Sorry you are having trouble.  Which version are you using?  Can you try the restart without specifying the ies num reals arg?

**Comment by RyanConway91** [comment]
I am using pestpp-5.0.10. I commented out the ++ ies_num_reals(48) and still am getting the same error.

**Comment by jtwhite79** [comment]
Ok.  One thing I'm nervous about is that the ies_par_en and the ies_obs_en are using the same file names as what ies is saving during initialization so those original files may have been stomped on.  Can you zip up that directory and post it here?

**Comment by RyanConway91** [comment]
The zip is too big. Here is a google drive link:
https://drive.google.com/file/d/1IEKPZ03L_Qe4CBVsPeiDft8rgpOCMml9/view?usp=sharing
Let me know when you have downloaded it so I can remove the link

**Comment by jtwhite79** [comment]
I requested access to the file...

**Comment by RyanConway91** [comment]
Should have access now, sorry about that

**Comment by jtwhite79** [comment]
got it - debugging now...

**Comment by jtwhite79** [comment]
ok, found the issue - there is a unique case here of restarting with the prior par ensemble by also using `ies_csv_by_reals = False`.  Ive got it patched and its testing now. I'll let you know once there is a pre-release that has this fixed.

**Comment by jtwhite79** [comment]
This issue should be fixed as of 5.0.11 [https://github.com/usgs/pestpp/releases/tag/5.0.11](https://github.com/usgs/pestpp/releases/tag/5.0.11).

Also, just curious about the number of iterations you are using - 19 seems pretty high for an ensemble method - I've rarely gone beyond 4-5 iterations.   I dont know your context/model/etc, just curious is all...

**Comment by RyanConway91** [comment]
Thanks!

Interesting. I just had the same model I sent you go 21 iterations on IES. In the past it has generally been less iterations (<10) and I am not sure why its going longer this time. I don't think I am using any strange convergence criteria or anything. I hadn't really thought about it, I just let it run. Does the high number of iterations indicate anything problematic about the parameterization of the model?

Looks like I could have stopped after 5 or 6 and basically have been there though:

![image](https://user-images.githubusercontent.com/25184697/109242415-b3cd9700-77a0-11eb-99d1-4a157dad137f.png)

**Comment by jtwhite79** [comment]
I see.  Those termination criteria are just based on phi changes across several iters.   My usual method of stopping is ctrl+c haha.  I usually look at that same plot you show and also look at the par change summary - when lots of pars start hitting bounds, probably time to quit.  I don't think there's any hard and fast rule but generally I think it's safer to accept earlier iters with higher phi values...
