### ISSUE TITLE
control file parsing error in PESTPP-SWP on pst file that runs fine with regular PEST

### ISSUE THREAD

**Issue by RyanConway91** [usgs/pestpp#126]
Hello, I am getting the following error:

checking model IO files...control file parsing error: error in model interface file checking:model input/output error:Error: the following observations were found in the control file but not in the instruction files:
DUMMY_OBS

This is a SWP run that is just sending .ucn files back for post processing, there are no real observations, so I have a single dummy observation. The model runs fine via PEST.

This is the pif:
pif @
@dummy_obs@ !dummy_obs!

**Comment by RyanConway91** [comment]
I changed the variable from dummy_obs to d and it worked. Does an observation called "dummy" make the code not work?

**Comment by jtwhite79** [comment]
Thanks for the heads up on this - was trying to be cheap when quickly parsing instruction files at startup to get obs names for comparing against the control file, and, to even cheaper, we were just checking that "dum" wasn't in the instruction token (to handle the "dum" placeholder), which incorrectly skipped "dummy_obs" ("dum" is in "dummy_obs").  So, the irony weighs heavy here: that was "dum" - haha!  Ive got a patch for this testing...

**Comment by RyanConway91** [comment]
Great! Thanks for looking into this
