### ISSUE TITLE
Prior parameter covariance matrix and PESTPP-OPT

### ISSUE THREAD

**Issue by Cecile-A-C** [usgs/pestpp#128]
Hello, I am using PESTPP-OPT with FOSM-based chance constraints. I generate my prior parameter covariance matrix using PyEMU:
```
sd = {'struct.dat': [os.path.join('pest_files', 'hk1pp.dat.tpl')]}
cov = pyemu.helpers.geostatistical_prior_builder(pst, struct_dict = sd, sigma_range = 4)
cov.to_binary('prior_cov_matrix.jcb')
```
Then I supply this matrix to PESTPP-OPT, also using PyEMU: `pst.pestpp_options['parcov'] = 'prior_cov_matrix.jcb'
`
But I get this error message when launching PESTPP-OPT:

> PANTHER master listening on socket: [ÿÿÿÿ]:4002 (IPv6)
> Error condition prevents further execution:
> Cov:try_from() error reading from file prior_cov_matrix.jcb :Mat::from_binary() error opening binary file prior_cov_matrix.jcb for reading

When looking at my parcov matrix in a text file, generated using `cov.to_ascii('prior_cov_matrix.txt')`, it looks fine, and my matrix also works fine if I use it for uncertainty analysis with the Schur complement.

Is my parcov matrix not compatible with PESTPP-OPT?

Thank you for your help. I am using version 5.0.9 compiled in December 2020.
[parcov_files.zip](https://github.com/usgs/pestpp/files/6689287/parcov_files.zip)

**Comment by jtwhite79** [comment]
Im able to read that parcov jcb without any trouble using 5.0.9 (the current master branch code).  That error message seems to indicate the pestpp-opt knows it is supposed to read a binary file named "prior_cov_matrix.jcb" but that it cant find the file in the current working directory where pestpp-opt is running.  Are you sure that file exists in the current working directory and that its not locked up with some kind of strange permissions or anything? If you are convinced this is a pestpp-opt issue, can you upload your full package of pest and model files?

**Comment by Cecile-A-C** [comment]
Thanks for your quick reply. It made me realize I was copying the parcov jcb to the workers only, and not to the manager as well. Everything works fine now. I will close the issue (or can delete it, if this is not relevant to others).
