### ISSUE TITLE
PESTPP-IES seems to stop writing .rei files after parameter sets are dropped

### ISSUE THREAD

**Issue by RyanConway91** [usgs/pestpp#129]
I have an IES run that had some parameter sets dropped during calibration.

After this occurred, IES continued to run as normal but stopped writing the pst.n.base.rei files and stopped writing to the pst.base.rei (where pst is the name of the control file)

I have the option parsaveitn specified. Here is shot of the directory:
![image](https://user-images.githubusercontent.com/25184697/123862288-c5a97d00-d8ed-11eb-800e-79ee69985414.png)

Also, the iteration numbers in the pst.base.rei file are all -1:
![image](https://user-images.githubusercontent.com/25184697/123862425-f12c6780-d8ed-11eb-9bdb-b4f9d2564bd9.png)

**Comment by jtwhite79** [comment]
Im guessing that means the "base" realization was one that was lost? The rec file would indicate which realizations were lost for each call to the run mgr - let us know if thats not the case.

**Comment by RyanConway91** [comment]
You are correct, the base realization was lost. Ill try and set up my compute pool so this doesn't happen next time. Thanks
