### ISSUE TITLE
read pest control file sections from external file

### ISSUE THREAD

**Issue by RyanConway91** [usgs/pestpp#130]
Is there a way to read sections of the control file (parameter and observation sections are the ones I am most interested in) from an external file to avoid having to copy them back into the control file manually?

**Comment by jtwhite79** [comment]
I'm not sure I understand exactly what you are looking for but the version 2 control file allows you to store par and obs data in one or more external csv files.  This format is described in the users manual and pyemu can flip a control file to this format if you are interested....

**Comment by RyanConway91** [comment]
Great thank you, that sounds like what I am after
