### ISSUE TITLE
SVD Assist - super_eigthresh default value

### ISSUE THREAD

**Issue by Smith0710** [usgs/pestpp#131]
Hi.
The PEST++ (v5.0.11) manual states "The default value for _super_eigthresh()_ is 1.0E-8". From my brief experience it appears this value is set two orders of magnitude larger (1.0E-6) if _super_eigthresh_ is not set explicitly in the control file. This can result in too few super parameters.
![image](https://user-images.githubusercontent.com/85672255/129684787-fee7e176-f36d-4f95-afe6-35a04dbc2751.jpg)

**Comment by jtwhite79** [comment]
I'll update the users manual.  I think we raised that defauly threshold because we were getting some really small singular components included in the super parameters which was leading to unstable solutions.

**Comment by Smith0710** [comment]
Sorry, didn't realise it was up to me to close the issue!
Thanks for your earlier reply, which I did read back in August.
