### ISSUE TITLE
PESTPP-SWP crashing after receiving first model run

### ISSUE THREAD

**Issue by RyanConway91** [usgs/pestpp#141]
I am using SWP on a set of MODFLOW models with very long run times (few days). When the first of runs finishes (after a few days), it appears that the master is crashing and stopping all the workers. There are no errors reported by the master CMD window, or in the rmr. In the panther_worker.rec, the error:

10/22/21 07:25:15->receive from master failed: MSP-GWModel1.barr.com:4004

Appears on all workers. 

If run the models with 1 iteration, the runs are very quick, and SWP works fine. Ive tried a hosting the master on a couple different machines and it keeps happening. 

I am using 5.0.11

Any ideas why SWP would for short run time but not a long one?

**Comment by jtwhite79** [comment]
@RyanConway91 - Im gonna close this issue for book keeping - feel free to reopen if the problem persists.
