### ISSUE TITLE
External file of template files: missing required column "MODEL_FILE"

### ISSUE THREAD

**Issue by ndeeds** [usgs/pestpp#143]
With what appears to be a correctly formatted external file of template files (created by PyEmu):

![image](https://user-images.githubusercontent.com/16090529/139275910-c6951283-ba04-4642-bb11-aa856da2a8f7.png)

ebh3u_tr_pest_v02.tplfile_data.csv:

![image](https://user-images.githubusercontent.com/16090529/139276444-3d41f995-eff2-40ad-adad-c312fc51a00e.png)

Throws "missing required column 'MODEL_FILE':

![image](https://user-images.githubusercontent.com/16090529/139276200-806e6749-d5ae-4d4e-9b15-e85c858eb644.png)

In pestpp_common/Pest.cpp

I think the goal of the code block is to look at the hard-coded list of columns that should be in the file, and determine if one of them is missing. What the line below appears to do is to throw the error if "MODEL_FILE" is the last column.

![image](https://user-images.githubusercontent.com/16090529/139274400-8709a497-d1d5-4e2d-91d8-0d1418d516cc.png)

**Comment by jtwhite79** [comment]
this has been fixed in 5.1.X
