### ISSUE TITLE
Control file setup problem - Coupling ATS and PEST++

### ISSUE THREAD

**Issue by radhakrishnabl96** [usgs/pestpp#144]
Hello all,

I have some issues is setting up the control file (see below). 
![image](https://user-images.githubusercontent.com/66324847/139652865-25eaa075-acc1-4210-aad8-02f17af97f35.png)

1. I downloaded PEST to run the PEST Utilities. I ran the command: **pestchek control_file_name** . It encountered the following error:

 **PESTCHEK Version 17.3. Watermark Numerical Computing.

 Errors ----->
 File rk_model_glm_cf.pst does not have correct PEST control file header.**

- The control file setup is based on the newer version of pest++, Can I still run the 'pestchek' utility? If yes, How do I modify the file to prevent this error? Does PEST++ have other utilities to check the control files?

2. Within the control file, I have the model command statement as **ats --xml_file="rk_model_glm_input.xml"**. rk_model_glm_input.xml is the input file that needs to be run along with the command ats --xml_file="...". Is this formulation right? (I have also provided the input file name in **rk_model_glm.tplfile.csv**). How does PEST++ access the input file and change the parameters later?

3. On running the command **pestpp-glm control_file_name**. It run the model one time and then encounters the following error:

**11/01/21 10:36:04 foward run command(s) finished, took 56.03 seconds
11/01/21 10:36:04 processing instruction files with 1 threads...
exception raised by run thread:  thread processing instruction file raised an exception: InstructionFile error in file 'rk_model_glm_obs_data.dat.ins' on instruction file line: 2, on _output file line: 576 : EOF encountered when executing line advance instruction_

  Error running model:  thread processing instruction file raised an exception: InstructionFile error in file 'rk_model_glm_obs_data.dat.ins' on instruction file line: 2, on output file line: 576 : EOF encountered when executing line advance instruction
 
  Aborting model run

-->11/01/21 10:36:04 run complete, took: 56.037 seconds
-->0 of 1 complete, 1 failed

    ---  serial run manager runs summary:  ---    
    0 of 1 complete, 1 failed
    process took : 56.037 seconds

WARNING: 1 out of 1 runs failed

    failed run ids:
0,

Model run failed.  No results were recorded.**
 
- What is in ' ...output file line: 576 : EOF encountered when executing line advance instruction'? How do I get to this output file and debug the problem? Is this the problem associated with my first issue?

Thank you!

Best Regards,
Radhakrishna.B.L.

**Comment by radhakrishnabl96** [comment]
I also ran the pest utilities - tempchek and inschek which showed that there was no error in the template and instruction files.

**Comment by jtwhite79** [comment]
It's hard to say what's happening.  First pest doesn't support the enhanced ctl file format so if you want to use pestchek, you'll need to convert back to the standard format - I think there is a pest utility for this and pyemu can do this conversion too.  If you are using a recent version of pest++, it will also perform some of the pestchek checks at startup.  It sounds like from that error that the model run took about 1 minute and then, when processing the output files with the instruction files, an end of file was encountered - looks like it read the output file to line 576.  This error usually happens when the forward run didn't run to completion.  Do you expect more than 576 lines in that model output file?  Did the model run as expected?

**Comment by radhakrishnabl96** [comment]
Thank you for your reply. I'll look into the pest utility and pyemu. 

1. What function do I run to carry out checking the pest control file in version 2?
2. No, I dont expect more than 576 lines in the model output file and the model ran as expected. I had more output variables in the output file compared to the instruction file variables, I changed them. I still get the same error:

**11/02/21 07:28:01 foward run command(s) finished, took 66.024 seconds
11/02/21 07:28:01 processing instruction files with 1 threads...
exception raised by run thread:  thread processing instruction file raised an exception: InstructionFile error in file 'rk_model_glm_obs_data.dat.ins' on instruction file line: 2, on output file line: 456 : EOF encountered when executing line advance instruction

 
  Aborting model run**

- I feel that I have not setup the instruction file properly. Do we have a PEST++ utility to generate instruction files from the model output? An example of my instruction file.
![image](https://user-images.githubusercontent.com/66324847/139799309-067b017e-992c-446c-a2dd-4971c6904a00.png)

- Do we need to discard all the model output files after each PEST iteration? (It generates a large number of files which we don't consider)

**Comment by radhakrishnabl96** [comment]
I have also attached the model output file for comparison:
![image](https://user-images.githubusercontent.com/66324847/139856383-86beb142-589a-46ec-97e6-e6cdbf17f4b5.png)

Any recommendations is greatly helpful!

**Comment by jtwhite79** [comment]
Ok, one thing I can see is that the instruction file is looking for commas (`~,~`) but the output file is whitespace delim.  Also, the output file has a header line with column labels, but the instruction file is not skipping that header line.  But those errors should have been encountered long before reaching output file line 456.  What does the instruction file listing in the control file look like?  It might be worth using inschek to test processing - you can feed inschek the name of an output file and it will try to read that output file.  You can convert to the v1 control file with pyemu like this:

```
import pyemu
pst = pyemu.Pst("my.pst")
pst.write("my_v1.pst",version=1)
```

**Comment by radhakrishnabl96** [comment]
It worked and the PESTpp program (for version=2) ran successfully!

1. I replaced the delimiter ~,~ with whitespace.
2. I removed the header line with column labels from my ats output file.

Thank you @jtwhite79!
