### ISSUE TITLE
Pcf run smoothly in serial or by the manager (in parallel), but not by the agents (in parallel)

### ISSUE THREAD

**Issue by BJEANNOT0** [usgs/pestpp#146]
Hello,

I am new to the pestpp-community, so my question may be somewhat dumb. Sorry in advance !
Here is my situation : 
-For a run in serial, the command line pestpp-XXX case.pst (with XXX being GLM or IES for example) manages to read my pest control file successfully. Here is what is displayed on screen
![image](https://user-images.githubusercontent.com/94854455/142893715-6bed8472-5057-46da-b2fb-b9d958204630.png)

-When doing a parallel run, the PCF is run smoothly by the manager (See the picture below) : 
![image](https://user-images.githubusercontent.com/94854455/142893874-5efc7a28-d659-4809-957f-696dc652a819.png)

-however, when running pestpp-xx as an agent, I get the following error :
![image](https://user-images.githubusercontent.com/94854455/142894014-7f7a6777-c646-4c34-943f-bd85a0079af4.png)

I emphasize that I ran the 3 command lines on the same directory, killing one before starting the next one.
I do not understand how the agent would not manage to read something the manager or the serial run read successfully
You will find my PCF attached (i renamed it case.txt to be able to send it on github)
[case.txt](https://github.com/usgs/pestpp/files/7582533/case.txt)

COuld you please help me understand what the issue is ?
Thanks in advance.
Best regards,

**Comment by jtwhite79** [comment]
This is a bug and Im testing a patch for it now.  In the meantime, you can use the standard "* model input/output" control file section format.

**Comment by jtwhite79** [comment]
5.1.5 fixes this issue - there is a release for it now.

**Comment by BJEANNOT0** [comment]
Thanks ! It looks like it solved my issue indeed.
Best regards,
