### ISSUE TITLE
Is there a way to save Pespp-outputs in a particular folder instead than in the same folder as the pest control file ?

### ISSUE THREAD

**Issue by BJEANNOT0** [usgs/pestpp#148]
Hello,

I would like to save Pestpp-outputs in a specific folder named for example"pest_output", this folder being in the same directory as the pest control file.
Is there a specific argument to do it in pestpp ? By default, all output files are automatically saved in the same folder as the pest control file , (not in a sub-folder).

Thanks in advance.
Best regards,

**Comment by jtwhite79** [comment]
not currently - when you start messing with paths and directories, bad times.
