### ISSUE TITLE
FOSM process with lots of tied/fixed parameters and 0 weighed observations

### ISSUE THREAD

**Issue by BJEANNOT0** [usgs/pestpp#152]
Hello,

I encounterted the following situation I would like to discuss.

-I am doing a parameter estimation with pestpp-glm
-I have 11085 parameters, but only 6 are adjustable (the others are either tied or fixed)
- I have 96360 observations but most of them are of weigh 0 (this is because I plan on using them later but not in the current parameter estimation), only 8760 have a weigh >0
-each run of my model takes approximately 2 minutes.

Now here is how the parameter estimation happens : 
-The model runs with a slight change of each parameters are calculated fairly quickly (even more when running pest++ in parallel)
-computing of upgrade vectors with different values of lambda is fairly quick
-FOSM process takes hours and hours. I undestand this is because i have a lot of non-adjustable parameters ans 0 weighed observations.

At the moment, I understand that I can use the two following options to speed up the process : 
-chosing not to do any FOSM analysis with the **uncertainty** option set to 0
-chosing to do FOSM analysis less often, with the **opt_recalc_fosm_every** option set to a value higher than 1.

However, is there a way to still do FOSM analysis every iteration, but without taking into account fixed/tied parameters neither 0-weighed observations ? Also, I noticed that running pestp-glm in parallel does not speed up the FOSM process. Would it be possible to gain time in FOSM process thanks to parallelizaiton techniques  ?

Thanks in advance for you response.
Best regards,

**Comment by jtwhite79** [comment]
Im not sure those FOSM routines that pestpp-glm uses have been tested with this many parameters and observations so its likely they could use some code optimization, probably related to forming the linear algebra components.  I'll take a look at that...

**Comment by BJEANNOT0** [comment]
Thank you !
Best regards,

**Comment by jtwhite79** [comment]
so Ive looked into this and it will be some open-heart surgery to optimize these routines.  But, more generally, the ensemble tools (pestpp-ies, pestpp-da) are designed and optimized for very large numbers of parameters and observations so Im wondering if you might be interested in trying those for this work?  I know you only have few adj parameters currently but Im guessing you included all those tied and fixed parameters because you recognize them as uncertain...anyway, just a thought.

**Comment by BJEANNOT0** [comment]
I will indeed end up setting all parameters as adjustable. As a consequence, I will most likely use pestpp-ies at some point. 
I will also look into pestpp-da that you are mentionning.  
Initially, since my model runs are somewhat quick, I was thinking I could still give a try to pestpp-glm, but I now understand that this may not be the best option.

Thank you for dealing with my issue.
