### ISSUE TITLE
Tied parameters in external parameter data section

### ISSUE THREAD

**Issue by BJEANNOT0** [usgs/pestpp#153]
Hello,

i do not manage to enter tied parameters in an external parameter data section.
I made an external file specifically for tied parameters and I added a column named "partied" in the file referencing tied parameters, but I keep getting this error : 
error condition prevents further execution : map :: at

Do you know what the problem might be ?
I send as an attachment an external parameter data section

[por_m_tied.txt](https://github.com/usgs/pestpp/files/7712793/por_m_tied.txt)

Thanks for your help.
Best regards,

**Comment by jtwhite79** [comment]
Can you post to full pest control file and external sections?  That parameter data section you posted only has one parameter listed...

**Comment by BJEANNOT0** [comment]
THanks for your quick answer.
Here is the whole set of files : 
[pcf.txt](https://github.com/usgs/pestpp/files/7712830/pcf.txt)

[model_input.txt](https://github.com/usgs/pestpp/files/7712834/model_input.txt)
[model_output.txt](https://github.com/usgs/pestpp/files/7712835/model_output.txt)
[per_m.txt](https://github.com/usgs/pestpp/files/7712837/per_m.txt)
[por_f.txt](https://github.com/usgs/pestpp/files/7712838/por_f.txt)
[por_m.txt](https://github.com/usgs/pestpp/files/7712839/por_m.txt)
[por_m_tied.txt](https://github.com/usgs/pestpp/files/7712840/por_m_tied.txt)
[emm_f.txt](https://github.com/usgs/pestpp/files/7712841/emm_f.txt)
[emm_m.txt](https://github.com/usgs/pestpp/files/7712842/emm_m.txt)
[flux_depression.txt](https://github.com/usgs/pestpp/files/7712843/flux_depression.txt)
[per_f.txt](https://github.com/usgs/pestpp/files/7712844/per_f.txt)
[per_l.txt](https://github.com/usgs/pestpp/files/7712845/per_l.txt)
[O_f_piez_FP007.txt](https://github.com/usgs/pestpp/files/7712846/O_f_piez_FP007.txt)

I can tell you that when I replace the file por_m_tied.txt by the file below, Pest++ runs without error 
[por_m_tied_nottied.txt](https://github.com/usgs/pestpp/files/7712873/por_m_tied_nottied.txt)

**Comment by jtwhite79** [comment]
got it - there is a bug in how using the "easy" names interacts with the identification and checking of tied parameters.   testing a fix right now, should have a new pre-release soon....

**Comment by BJEANNOT0** [comment]
Thank you ! I switched to "old" names and it worked.

**Comment by jtwhite79** [comment]
This should be fixed as of 5.1.9.  Feel free to reopen this issue if not.

**Comment by BJEANNOT0** [comment]
Thabk you !
