### ISSUE TITLE
Case.par contains values of parameters at the last iteration; not values at the best iteration

### ISSUE THREAD

**Issue by BJEANNOT0** [usgs/pestpp#154]
Hello,

I noticed that after the end of the inversion process, case.par does not contain the value of parameters at the best iteration. Rather, it contains the values of parameters at the last iteration.
I am a bit surprised by this behavior. Is this intended ?
Thank you for your help.

You will find as an attachment : 
my .par file
my .iobj file
the.par file for the best iteration and for the last iteration.

[case.iobj.txt](https://github.com/usgs/pestpp/files/7735310/case.iobj.txt)
[case.par.txt](https://github.com/usgs/pestpp/files/7735311/case.par.txt)
[case.11.par.txt](https://github.com/usgs/pestpp/files/7735312/case.11.par.txt)
[case.15.par.txt](https://github.com/usgs/pestpp/files/7735313/case.15.par.txt)

Best regards,

**Comment by jtwhite79** [comment]
You are probably right that the .par file will just contain the latest iteration not the lowest-phi iteration.  I'll take a look at this.

**Comment by jtwhite79** [comment]
This should be fixed in pre-release 5.1.9

**Comment by BJEANNOT0** [comment]
Thank you!
Best regards,
