### ISSUE TITLE
Error when running Pestpp-ies : EnsembleMethod error: run_ensemble() error: error running ensemble: Error in RunStorage routine: run id = 606 is not valid.  Valid values are 0 to -174857410

### ISSUE THREAD

**Issue by BJEANNOT0** [usgs/pestpp#158]
Hello,

i just got this error when using pestpp-ies : 

"EnsembleMethod error: run_ensemble() error: error running ensemble: Error in RunStorage routine: run id = 606 is not valid.  Valid values are 0 to -174857410"

(i was doing a parameter estimation with 800 realizations)
Do you have any idea where this problem can come from ? I am a bit doubtful because I was doing a copy paste from my manager folder to another  (unrelated) folder at the very moment I got this error (not a cut/paste, just a copy/paste), could this have caused the error ? I will run again the parameter estimation process to make sure and keep you updated, but I wanted to post my question right now while I am focused on the problem.

Just in case, I send as an attachment my case.rec and case.rmr file, and my pest control file.
[case.pst.txt](https://github.com/usgs/pestpp/files/7889737/case.pst.txt)
[case.rec.txt](https://github.com/usgs/pestpp/files/7889730/case.rec.txt)
[case.rmr.txt](https://github.com/usgs/pestpp/files/7889731/case.rmr.txt)

Thank you for your insights ! I will keep you updated.
Best regards,

**Comment by BJEANNOT0** [comment]
update : From tests I have just done, the problem seems unrelated to copy/pasting.
I will try to replicate the error by running again my simulation (it takes several hours therefore i will give you an update tomorrow)
Bets regards,

**Comment by jtwhite79** [comment]
This error shows up intermittently and randomly for me and I've not been able to make it happen consistently.  My current thinking is that is related to the temporary run storage file that the run manager uses - this file gets accessed often and if the file gets too large or corrupt, I think this is when the error happens.  If you get to a point where it happens consistently for you, please let me know!

**Comment by BJEANNOT0** [comment]
Thank you for your answer.
I ran the exact same simulation and did not manage to replicate the error, as you guessed. Sorry !
I will keep you updated if I manage to get it consistently.

**Comment by BJEANNOT0** [comment]
Sorry to come back with new problems, but I got another error that might be related : 
"terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc"

The error occured when pestpp-ies was testing different lambdas values. Have you already got this one before ?

Once again I was copy pasting files from an agent to an unrelated folder when the error occured.I have the feeling that when there are lots of parameters and observations, folders used by pestpp must be totally left alone during the inversion so as to prevent this kind of error- I might be wrong though !
Thanks again for your hhelp.

**Comment by jtwhite79** [comment]
ok that's a good clue.  That `bad_alloc` happens whenever C++ doesn't get the contiguous memory it requested.  So this means you may be running low on memory (this could also explain the run storage). Can you monitor the available memory on the master host machine?  Are you also running workers on the same host machine as the master?  If so, it might worth reducing the number of workers...

**Comment by BJEANNOT0** [comment]
Thank you. I have indeed agents on the same machine as the manager. I will reduce their numbers from now on.
Best regards,
