### ISSUE TITLE
map::at: key not found error when generating DE population in pestpp-mou

### ISSUE THREAD

**Issue by kmarkovich-intera** [usgs/pestpp#161]
I'm running a simple test of pestpp-mou using Freyberg, and am encountering the following error after the first population is run:

  ---  initialization complete  ---  

  ---  starting iteration  1  ---  
WARNING: 1 duplicate solutions found, dropping (see rec file for listing)
99 feasible solutions
...generating diffevol population of size 100
Error condition prevents further execution: 
map::at:  key not found

See the attached template directory. 
[simple_freyberg_template.zip](https://github.com/usgs/pestpp/files/7937722/simple_freyberg_template.zip)

In case it matters, I am running the following gcc version: 
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-apple-darwin19/9.2.0/lto-wrapper
Target: x86_64-apple-darwin19
Configured with: ../gcc-9.2.0/configure --build=x86_64-apple-darwin19 --disable-nls --enable-checking=release --with-system-zlib --disable-multilib --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk --enable-languages=c,c++,fortran --with-gmp=/usr/local --with-mpc=/usr/local --with-mpfr=/usr/local
Thread model: posix
gcc version 9.2.0 (GCC)

**Comment by jtwhite79** [comment]
This should be fixed in release 5.1.10.
