### ISSUE TITLE
weights of inf should bomb

### ISSUE THREAD

**Issue by mnfienen** [usgs/pestpp#164]
OK, it's user error that I assigned some infinite weights to sreamflows (oops! 10/Q when Q is zero) but this results in PHI=NaN. It would be nice if pestpp would bomb and tell me I'm dumb rather than run to completion and report NaN. Just a thought  :) - it was a NOPTMAX=0 run to test, but nonetheless cost some time.

**Comment by jtwhite79** [comment]
agreed.  we might also want to add similar to checks in `pyemu.Pst.write()`

**Comment by jtwhite79** [comment]
This is fixed now on `develop`
