### ISSUE TITLE
PESTPP-SWP: fixed parameters and CSV file

### ISSUE THREAD

**Issue by Cecile-A-C** [usgs/pestpp#167]
Hi,

I am using PESTPP-SWP, release 5.1.9. The manual (v5.1.10) says "_If a parameter is fixed in the PEST control file, and the value provided for that parameter in the CSV or JCO/JCB file differs from that in the PEST control file, the value in the PEST control file overrides that in the CSV or JCO/JCB file._" But in my PESTPP-SWP runs, the fixed parameter values in the PEST file don't seem to override the values in the CSV file. Is this an issue?

I am using PESTPP-SWP to obtain a model run for each parameter realization in a _parens.csv_ file, but changing the pumping rates (fixed 'qmuni' parameters) to 0. Here I ran PESTPP-SWP 3 times ([SWP results - compare.zip](https://github.com/usgs/pestpp/files/8018835/SWP.results.-.compare.zip)): 1) with my original files (qmuni = 1E-4 m3/s in the .pst _and_ the .csv), 2) with the original files but qmuni = 0 in the .pst _only_ (and still 1E-4 m3/s in the .csv), 3) with the original files but qmuni = 0 both in the .pst _and_ the .csv.
The _sweep_out.csv_ obtained from PESTPP-SWP run 2) is identical to the original run 1) (i.e. the non-null pumping rates are still being applied), but I assumed it should be identical to run 3) (i.e. null pumping rates).

Thank you for your help!

**Comment by jtwhite79** [comment]
@Cecile-A-C - that is a typo.  `pestpp-swp` handles fixed parameters and an existing ensemble like `pestpp-ies` does.  If a parameter is fixed but there is a corresponding column in the existing parameter ensemble, then the values in that column of the par ensemble are used (and `pestpp-ies` wont try to change them).  However, if a parameter is fixed and doesn't have a column in the parameter ensemble, then each model run will use the control file value  (the same for that fixed parameter is used for all model runs).  Let us know if that is not the behavior you are seeing...

**Comment by Cecile-A-C** [comment]
Ok, thanks for your answer @jtwhite79. I just tried another PESTPP-SWP run with a _parens.csv_ file where I removed the nine 'qmuni' columns, but I got this error:
![image](https://user-images.githubusercontent.com/59694240/152886559-4a591037-9e65-4d2c-8ea7-e0943e7d3b26.png)

Here are the files: [model_files_qmuni_cols_removed.zip](https://github.com/usgs/pestpp/files/8019338/model_files_qmuni_cols_removed.zip)

**Comment by jtwhite79** [comment]
forgot to mention there is a `sweep_forgive(true)` arg that lets you supply an input file with one or more "missing" parameters (including fixed ones).

**Comment by Cecile-A-C** [comment]
It works as expected with sweep_forgive(true). Thank you, I am closing the issue!
