### ISSUE TITLE
.sen only produced for GLM, not IES

### ISSUE THREAD

**Issue by wkitlasten** [usgs/pestpp#17]
No sensitivities are written to the .sen file when using IES (.sen file created, but no info). Also, no mention of .sen for IES in the manual, only for GLM. Maybe this is intentional since the jco is only approximate in IES?

Is there an easy way to look at sensitivities from IES, or is that silly? I assume ies_verbose_level(2) will save the jco, but then storage becomes an issue. Perhaps I pass an obs.csv and par.csv in pyemu to get a jco?

**Comment by jtwhite79** [comment]
That is a good question.  pestpp-ies never forms a jacobian matrix - it wont fit in memory for big problems, so no sensitivities either (that file being opened by default - I'll turn that off).  

The best alternative is probably the correlation coefficient between a par and an obs - with autoadaloc and high verbose level, ies will write these out.  You can also calculate them pretty easily with pandas.  This paper from Anderson shows how the CC can be related to a regression coefficient:
[https://journals.ametsoc.org/doi/pdf/10.1175/MWR-D-11-00013.1](https://journals.ametsoc.org/doi/pdf/10.1175/MWR-D-11-00013.1).  With those, you could, for each par, calculated a composite regression coefficient - maybe something that should be added to pyemu?

**Comment by jwhite-usgs** [comment]
as of 4.2.13, the ununsed file handles are no longer opened by ies.
