### ISSUE TITLE
PESTPP-OPT stack-based constraint uncertainty

### ISSUE THREAD

**Issue by Cecile-A-C** [usgs/pestpp#172]
Hello,

I am using PESTPP-OPT (v5.1.9) to run stack-based chance constrained optimizations. I would like to retrieve constraint standard deviations at each iteration.

I tried extracting stdev values from the _.obs_stack.csv_ files (reading them in Python and using pandas.DataFrame.std), but the stdev values I obtain (order of magnitude < 10m) are very different from the ones printed to the _.rec_ file (order of magnitude ~ tens of meters). How exactly are the stdevs in the _.rec_ calculated? I can post my files if needed.

Thank you,
Cecile

**Comment by jtwhite79** [comment]
There is a bug in reporting the empirical stack stdev and I've got a patch for this running.  It's only a rec file reporting issue - it doesn't affect the mechanics of the process (whew!)

**Comment by Cecile-A-C** [comment]
Ok, thank you for looking into it!

**Comment by jtwhite79** [comment]
@Cecile-A-C this should be fixed now on `develop`.  Let us know if you need new binaries...

**Comment by Cecile-A-C** [comment]
Yes it's fixed now. Thanks for your help once again.
