### ISSUE TITLE
PEST-IES. Ensemble method error

### ISSUE THREAD

**Issue by tamvejar** [usgs/pestpp#183]
Hi! I'm trying to use PEST-IES with a transient model, but after it's execution the agent console and log file showed me the following, respectively: 

![image](https://user-images.githubusercontent.com/94867641/164801928-209ad5e7-89c7-43e1-9929-0807bf40ce1f.png)
![image](https://user-images.githubusercontent.com/94867641/164801905-58c30988-1084-4dcb-9d5d-3b617ff3ea1e.png)

I'm not sure if the error is related to the ensemble file or the model batch (named “pestgv_PP”), but I couldn't find the error in any of them. (I've already run the same model with pest-hp and I had any problem)

Thanks in advance. Best regards.

**Comment by jtwhite79** [comment]
The error message you seek in in about the middle of that screenshot:

![image](https://user-images.githubusercontent.com/1770912/164814040-fc2d1ecd-adbf-4065-ae41-0613a020247c.png)

The model run command `pestgv_PP` did execute (or the OS didn't know what to do with it).

**Comment by tamvejar** [comment]
in order to use pest-ies, I've to modify something in the model run command?

**Comment by jtwhite79** [comment]
Actually, all of the PEST++ tools run just like PEST(_HP).  Looks like that exception is happening for a worker, so Im guessing something might be up with your env vars.  Have you been able to run pest in parallel using the same physical host machines from the command line?

**Comment by tamvejar** [comment]
Yes, using pest-hp I could run in parallel using the same physical host machines with the same model run command that I'm trying to use with pest-ies

**Comment by jtwhite79** [comment]
Can you add the extension to the model command - If its an executable, then the command becomes "pestgv_PP.exe".  There might be some differences in how fortran and C++ system calls are executed (maybe..)

**Comment by tamvejar** [comment]
yes, that was the error. Thank you so much!
