### ISSUE TITLE
PESTPP-GLM failing in 5.1.16 on Linux

### ISSUE THREAD

**Issue by ecudhi** [usgs/pestpp#184]
Hi. I've just updated from version 5.0.0 to 5.1.16 and am having trouble running pestpp-glm with Panther on Linux. The error message I get is:

_04/26/22 06:59:07 processing template files with 1 threads...
thread 0 processed 1 template files
04/26/22 06:59:07 done, took 0.012 seconds
04/26/22 06:59:07 calling forward run command(s)
04/26/22 06:59:07 calling forward run command: 'run_model.bat' 
exit_code: 3434
status: 256
exception raised by run thread: waitpid() returned error status for command: run_model.bat_

I had a look at the code, and located the problem in **model_interface.cpp**, line 751

```
int status = 0;
pid_t exit_code = waitpid(command_pid, &status, WNOHANG);
//if the process ended, break
if ((exit_code == -1) || (status != 0))
{
  finished->set(true);
  cout << "exit_code: " << exit_code << endl;
  cout << "status: " << status << endl;
  throw std::runtime_error("waitpid() returned error status for command: " + cmd_string);
}
```

The condition in the if statement met, because in my case status is non-zero. In version 5.0.0 the status clause was not present in the condition. Looking at the documentation for waitpid(...), maybe status being non-zero does not necessarily indicate an error? Perhaps replacing **status != 0** with **!WIFEXITED(status)** would be a better solution?

**Comment by p-ortega** [comment]
hey @jtwhite79 I wonder if this was something related to the linux distro?

I'm moving a pest setup from windows to linux and I'm encountering this error.

Ubuntu 22.04 in WSL using pestpp-ies 5.2.12 ..

**Comment by jtwhite79** [comment]
I've been running on 22.04 for a while locally without issues.  Can you wrap the forward run in an sh script or py and catch and report the return code to see what it is?

**Comment by jtwhite79** [comment]
Thinking about this more, I'll just have the model interface class in pest++ report the return info the stdout since it seems to be important

**Comment by p-ortega** [comment]
Classic windows .. I suspect I was running out of ram when interpolating, wsl is pretty ram-hungry..

I restarted and killed a bunch of processes and now it's all good.
