### ISSUE TITLE
run_ensemble() error in iteration 5 with ies

### ISSUE THREAD

**Issue by wkitlasten** [usgs/pestpp#185]
Any idea what might have happened here so I can avoid it in the future? I had 3 ies runs going on the same cluster, same master, different ports. 2 finished without an issue, the other (larger) one did this:

![image](https://user-images.githubusercontent.com/14982084/165381971-a691d4f3-a0d3-43b2-a8d4-44fbafafceb9.png)

Memory issue maybe?

**Comment by jtwhite79** [comment]
This happens to me when the disk gets full...any chance that happened here?  I just added traps for this in the most recent develop version so that if the run storage file cant be allocated and filled, it bombs before the runs....

**Comment by wkitlasten** [comment]
Storage on master seems fine. Entirely possible I left some orphan directories on the workers.


Thanks
