### ISSUE TITLE
restart of an interrupted PEST++-glm run

### ISSUE THREAD

**Issue by oscarfasanchez** [usgs/pestpp#190]
Hello!, I was trying to restart a Glm run, set by Pyemu, but I got the following mistake( i'm using pestpp-5.1.1)
rec file:
![image](https://user-images.githubusercontent.com/39230212/169148216-376219c7-794c-4b6b-887b-cbe8e1fc0bcf.png)
output:
![image](https://user-images.githubusercontent.com/39230212/169148260-afa56f86-1755-4687-96e9-3bcea6f09fb2.png)
more details of my project are in this issue:
https://github.com/pypest/pyemu/issues/334
I was using  "n_iter_base"=1 and "n_iter_super"= 2 
and superparameter iteration failed just before my PC shut down
rec file again:
![image](https://user-images.githubusercontent.com/39230212/169149055-311699c4-d9f1-4bf2-85f5-ced193356871.png)

I'd appreciate any help

**Comment by jtwhite79** [comment]
Ive worked a little more on the glm restart...this should work now...
