### ISSUE TITLE
Troubles detecting "double" variable type using pestpp-IES

### ISSUE THREAD

**Issue by sebmeng** [usgs/pestpp#196]
Hello Community!

I am using the pestpp-ies executable to run a parameter estimation with 34351 parameters, with the NOPTMAX variable set to 0. The model runs without problems, but when it is calculating the phi contribution for each observation group (three in this case), I am getting the following exception: 
![image](https://user-images.githubusercontent.com/48210348/177884045-0a372cd2-200e-4820-9f13-9597554f9ed1.png)

it does not recognize the value "-0.147700" as a double. 
the smptrend_psah_sim.smp file is shown below:

![image](https://user-images.githubusercontent.com/48210348/177884412-14d1b79a-f760-4d71-be56-303358f9424f.png)

the first four numbers in that file are recognized as doubles, but the following number is not. Since this file is obtained using a groundwater utility, it is not possible to change the number format every time the model runs,

Is there something that I am missing?

Thank you in advance for your responses,

Kind regards,

Sebastian Mengual

**Comment by cnicol-gwlogic** [comment]
Try using whitespace delimiters in your instruction file, rather than fixed format. Eg:
pif ~
w w w w !obsname1!
w w w w !obsname2!
...


Fyi Pyemu function pyemu.utils.smp_utils.smp_to_ins() will write the ins files for you from smp files. There is another function for CSV files too. Both make life a lot easier.

**Comment by jtwhite79** [comment]
I think the issue is that you are using "fixed format" instructions which are pretty strict (can we see the instruction file or atleast the first few lines?) - those trailing whitespaces are considered invalid for fixed format.  As @cnicol-gwlogic  mentioned, the other instructions are more forgiving.  

What version of pestpp-ies are you using?

**Comment by sebmeng** [comment]
[smptrend_psah_sim.zip](https://github.com/usgs/pestpp/files/9072712/smptrend_psah_sim.zip)
I've attached the file and here is a screenshot of the first lines:

![image](https://user-images.githubusercontent.com/48210348/178010622-11990a3b-a1bb-497f-a65a-81933d99407b.png)


I am using the [5.1.17](https://github.com/usgs/pestpp/releases/tag/5.1.17) Pre-release
 version of PESPP-IES
I will go with the @cnicol-gwlogic advice for now,

Thank you both for your help!

Regards

**Comment by sebmeng** [comment]
With the @cnicol-gwlogic advice it worked just fine with the NOPTMAX=0 option, thank you! But now I'm having another kind of issue. Using the NOPTMAX>0 option and parallelizing the PESTPP-IES simulation, I don't get any results because the model fails to run. Checking the files, I get the following difference in the Kx file for layer 1 of my model (it could be other differences):
- With the NOPTMAX=0 option, I get this "kx_1.dat" file, which has the correct values for each zone: 
![image](https://user-images.githubusercontent.com/48210348/178358052-466f2608-a7ce-4fa2-8754-4006b64350e2.png)

- With the NOPTMAX>0 option, I get this "kx_1.dat" file, which has incorrect values for each model zone (and therefore the model fails to run): 

![image](https://user-images.githubusercontent.com/48210348/178358355-0411137d-060e-4008-87d1-c2629514a7db.png)

I've attached the PST file: 
[temp5_reg.zip](https://github.com/usgs/pestpp/files/9087561/temp5_reg.zip)
 PD: If I run this simulation without parallelizing it, I'm still having this issue.

Thanks again for your valuable help,

Regards

**Comment by jtwhite79** [comment]
Its hard to say exactly what is going on but in the control file, the upper and lower parameter bounds are pretty extreme (looks like defaults of e+10, e-10) and ies uses these bounds to generate the prior parameter ensemble.  So I think what you are seeing is realized kx field (after pilot point values are interpolated to the grid).  This is probably why the kx values are so extreme...I bet if you checked temp5_reg.0.par.csv, you would likely see some pretty wild values...

Also note, ies disregards prior information equations - just fyi...

**Comment by sebmeng** [comment]
Thanks for your help Jeremy, adjusting the parameter bounds IES now runs without a problem! Now I have to run some test with the IES parameters, so I will close this issue.

Thanks again!
