### ISSUE TITLE
error during calibration with pestpp-glm

### ISSUE THREAD

**Issue by Marc78160** [usgs/pestpp#198]
I have this error during the calibration process:

_OPTIMISATION ITERATION NUMBER: 4

  Iteration type: base parameter solution
  SVD Package: RedSVD
  Model calls so far : 245

  Starting phi for this iteration                     Total : 858.987

  Contribution to phi from observation group       "obgnme" : 858.987
  Contribution to phi from observation group  "regulzn_hk0" : 1.92172e-12
  Contribution to phi from observation group  "regulzn_hk1" : 1.89454e-12
  Contribution to phi from observation group  "regulzn_hk2" : 2.14382e-12
  Contribution to phi from observation group  "regulzn_hk3" : 2.09067e-12
  Contribution to phi from observation group  "regulzn_ss0" : 4.07235e-11
  Contribution to phi from observation group  "regulzn_ss1" : 2.79524e-12
  Contribution to phi from observation group  "regulzn_ss2" : 3.57404e-12
  Contribution to phi from observation group  "regulzn_ss3" : 2.36405e-12
  Number of terms in the jacobian equal to zero: 3896 / 459934 (0.85%)

    Parameters whose perturbation runs failed while computing jacobian
      Parameter     Failed
        Name        Value
      ----------  ------------
  HK2_ZONE:7.0__ZN   0.000231214

    ---  Solving for regularization weight factor   ---
    Starting regularization weight factor      : 1e-10
    Starting measurement objective function    : 858.987
    Starting regularization objective function : 1.62237e-11
    Target measurement objective function      : 85.8987

Jco::get_matrix(): the following par names are not in the matrix: HK2_ZONE:7.0__ZN
Error encountered, cannot continue_

I guess it is because the corresponding run has failed,  but i have selected the ++der_forgive(true). In my understanding, shouldn't PEST freeze the parameter when a run failure is encountered in order not to stop the calibration process?

Best regards, Marc

**Comment by jtwhite79** [comment]
Hey @Marc78160 you are correct that with derforgive, the process should continue.  What version of pestpp-glm are you using?  Ive recently tested this situation and, at least on the develop branch and with the simple test problem I was playing with, pestpp-glm tolerated failed derivative runs...Any chance you can zip and upload your working directory so I can see the files?

**Comment by Marc78160** [comment]
Thank you for your answer. I've tried to investigate the problem a little bit, and i found something weird for you. In fact, the calibration goes to the end with pestpp-glm version 5.0.0 but neither with versions 5.1.6 not with 5.1.17 (where i got the above error)...

Please find the pest files if you are interested in investigating the cause of the pb
Thanks, Marc
[case_to_transmit.zip](https://github.com/usgs/pestpp/files/9220013/case_to_transmit.zip)
c

**Comment by jtwhite79** [comment]
Thanks for the heads up and the files - debugging now....

**Comment by jtwhite79** [comment]
This should be fixed in version 5.1.18

**Comment by oscarfasanchez** [comment]
Oh I  think I had the same problem using pest-glm 5.1.17
460 runs complete :  2 runs failed
![image](https://user-images.githubusercontent.com/39230212/185019219-3a88d3db-dea3-4b93-8435-553ce8ba2235.png)
I'll try with 5.1.18
is it now possible to restart using the base_jacobian with a jacobian missing two derivatives?

**Comment by jtwhite79** [comment]
Probably just to mark those two parameters as fixed in the control file.  Otherwise you fill a new jco with just those two pars and then splice the jcos together.

**Comment by oscarfasanchez** [comment]
the second option sounds nice, how can I splice two jcos? is there a pyemy function to do it??

**Comment by jtwhite79** [comment]
yup there is:

[https://pyemu.readthedocs.io/en/develop/pyemu.mat.html#pyemu.mat.mat_handler.concat](https://pyemu.readthedocs.io/en/develop/pyemu.mat.html#pyemu.mat.mat_handler.concat)

**Comment by oscarfasanchez** [comment]
thanks for the help @jtwhite79
I tried with:
import pyemu
import os
path1=os.path.join("01_orig" ,"model_pest.jcb" )
jco = pyemu.Jco.from_binary(path1)


path2=os.path.join("02_complement" ,"model_pest.jcb" )
jco2 = pyemu.Jco.from_binary(path2)

mats=[jco, jco2]
jco_new=pyemu.mat.concat(mats)
jco_new.to_binary("model_pest2.jcb")

but when I run pest-glm 5.1.18, it finishes after some time without doing anything(no error, no warning):
.log:
time,elapsed_seconds,message
22:44:31,5.06e-05,PEST++ performance logger started
22:44:31,0.0005714,starting to process control file
22:44:31,0.17661,finished processing control file
22:44:32,0.225502,loading parcov
.rmr:
PANTHER master listening on socket:0.0.0.0:4004 (IPv4)
.rec(end):
![image](https://user-images.githubusercontent.com/39230212/185743685-a42ea73c-2439-4ca5-bfa4-0f8c764aa5f9.png)


what am I doing wrong?

thanks for any help

**Comment by jtwhite79** [comment]
From what you show I think it should be working (or at least exiting more gracefully).  Can you post that master dir?

**Comment by oscarfasanchez** [comment]
![image](https://user-images.githubusercontent.com/39230212/185790203-280f61a6-c030-4e5a-bc21-26d79cc52df6.png)

sure, it takes almost three hours to do nothing.
although my task manager says that it's working
![image](https://user-images.githubusercontent.com/39230212/185774335-ffcbe570-7e94-4f5e-9fe1-2cacaf7b4a19.png)

**Comment by jtwhite79** [comment]
Can you zip and post the contents of the master dir?

**Comment by oscarfasanchez** [comment]
oh sorry😅,
https://correouisedu-my.sharepoint.com/:f:/g/personal/oscar2198138_correo_uis_edu_co/Ev0jLJ7k5oNKpk_axdTxqJEBxwT78W0yHzgmd6Ix1k62Xw?e=GYYCsN

**Comment by jtwhite79** [comment]
The `model_pest2.jcb` looks goofed - its smaller than `model_pest.jcb` and I cant read it with pyemu either.  Can you post both of the jcbs that you combined to make the updated jcb? Is `model_pest.jcb` one of those?

**Comment by oscarfasanchez** [comment]
oh, here it is
model_pest.jcb is the main file, the other one I did it freezing all the successful parameters in the jacobian process
https://correouisedu-my.sharepoint.com/:f:/g/personal/oscar2198138_correo_uis_edu_co/Ev0jLJ7k5oNKpk_axdTxqJEBOF11JTZmlWhkvoW6UMn6eg?e=RK5c56

**Comment by jtwhite79** [comment]
Ok, this is what I did and pestpp-glm at least reads the `new.jcb` jacobian and wants to run the model once:
```
import os
import pyemu
j1 = pyemu.Matrix.from_binary(os.path.join("01_orig","model_pest.jcb"))
j2 = pyemu.Matrix.from_binary(os.path.join("02_complement","model_pest.jcb"))
j3 = pyemu.mat.mat_handler.concat([j1,j2])
j3.to_coo("new.jcb")
```

Can you try that?

**Comment by oscarfasanchez** [comment]
![image](https://user-images.githubusercontent.com/39230212/186047045-3d285ad7-ae2c-4e73-a08e-6276db503b65.png)
Great! now it is working!
Thank you very much!
