### ISSUE TITLE
pestpp-ies not writing observation realisations to case.N.obs.csv and case.obs+noise.csv

### ISSUE THREAD

**Issue by Smith0710** [usgs/pestpp#199]
It appears that pestpp-ies (from at least v 5.1.16) is writing only the base case observation values to these files and omitting the realisations values. An earlier version (v. 5.0.11) installed with GWV is successfully writing the realisation values. Thank you.

**Comment by jtwhite79** [comment]
Can you provide a rec file for a run where this has happened?

**Comment by Smith0710** [comment]
Thanks for taking a look at this @jtwhite79 . Note the control file contains prior information that I did not remove as pestpp-ies reports it ignores these data.
[pest.zip](https://github.com/usgs/pestpp/files/9279084/pest.zip)

**Comment by Smith0710** [comment]
Oops, sorry, the rec file! I'm uploading one rec file produced by pestpp-ies v. 5.0.11 ('rec_file_successful.rec') and one produced by v. 5.1.18 ('rec_file_unsuccessful.rec')
[rec_file_unsuccessful.zip](https://github.com/usgs/pestpp/files/9279195/rec_file_unsuccessful.zip)
[rec_file_successful.zip](https://github.com/usgs/pestpp/files/9279194/rec_file_successful.zip)

**Comment by jtwhite79** [comment]
I don't see anything out of the ordinary with those files - both rec files indicate that the obs+noise and initial obs ensembles are being saved to disk. Just to be clear, ies (along with the other pest++ tools) are running lots of CI tests every day and many of those tests require that those two files are available after a run.  But, Im not saying its impossible that this could happen! If you are sure that ies isnt writing those files, can you send me those two master dirs so I can dig in further?

**Comment by Smith0710** [comment]
Thanks for your reply. The problem I am seeing is missing information is these files rather than the files themselve not being written. In the 'unsuccessful' case only the base obsevations are included in the files and the realisation/ensemble values are missing. I can upload example files (when back at my computer) if that would help?Sent from my Galaxy
-------- Original message --------From: J Dub ***@***.***> Date: 9/8/22  6:44 am  (GMT+08:00) To: usgs/pestpp ***@***.***> Cc: Smith0710 ***@***.***>, Author ***@***.***> Subject: Re: [usgs/pestpp] pestpp-ies not writing observation realisations to case.N.obs.csv and case.obs+noise.csv (Issue #199) 
I don't see anything out of the ordinary with those files - both rec files indicate that the obs+noise and initial obs ensembles are being saved to disk. Just to be clear, ies (along with the other pest++ tools) are running lots of CI tests every day and many of those tests require that those two files are available after a run.  But, Im not saying its impossible that this could happen! If you are sure that ies isnt writing those files, can you send me those two master dirs so I can dig in further?

**Comment by jtwhite79** [comment]
I'd like to see those files sure.  How do the following iteration obs ensemble files look?

**Comment by Smith0710** [comment]
Yes, each iteration of files look the same with regard to missing the ensemble values. I have uploaded the obs file sets for the two cases. Thanks
[obs_files_successful.zip](https://github.com/usgs/pestpp/files/9297344/obs_files_successful.zip)
[obs_files_unsuccessful.zip](https://github.com/usgs/pestpp/files/9297348/obs_files_unsuccessful.zip)

**Comment by jtwhite79** [comment]
hmm.  Can you share the master dir for the unsuccessful run?  I cant make this happen with the test problems I have...

**Comment by Smith0710** [comment]
Apologies for the time this is taking - I hope the cause it not just something stupid I have done! Here is the master folder. The model is a simple hypothetical setup I'm using to learn and test things out. The run is executed via a Jupyter notebook. The model files were build initially using GWV and the ies run is set up in the notebook using flopy and pyemu. Before running pestpp-ies, the ies executable is copied into the workspace. The successful case occurs using v. 5.0.11 from myGWV folder and the unsuccessful case occurs using v. 5.1.18 copied from my pestpp bin folder. Thanks.
[EX1_ies_master.zip](https://github.com/usgs/pestpp/files/9313622/EX1_ies_master.zip)

**Comment by jtwhite79** [comment]
Well, you were right.  It was related to using an existing ensemble with realization names other than the names ies (and pyemu) generate by default - that was the blind spot here.  Ive got a patch testing now, this will be fixed in 5.1.20.  Thanks for the heads up!

**Comment by Smith0710** [comment]
Thanks very much for getting to the bottom of this one. Much appreciated!
