### ISSUE TITLE
"reg_factor" seems off, or I don't understand the message

### ISSUE THREAD

**Issue by wkitlasten** [usgs/pestpp#2]
I had reg_factor(0.1). The doc says:

> The value assigned to this weight factor is such that the “regularization objective function” is equal to a **fraction F of the current value of the objective function** which characterizes model-to-measurement misfit. F is the value assigned to the ies_reg_factor() control variable.

The .rec file output says:

```
...phi summary for entire ensemble using lambda,scale_fac 1.2e+08 , 1 , 
       phi type           mean            std            min            max
      composite    3.72894e+11    9.01699e+09    3.57824e+11    3.94587e+11
       measured    3.72894e+11    9.01699e+09    3.57824e+11    3.94587e+11
 regularization        8428.79        1413.34        2256.48        10491.6
         actual    3.72894e+11    9.01684e+09    3.57824e+11    3.94586e+11
     current reg_factor: 0.1
     note: regularization phi reported above does not 
           include the effects of reg_factor, 
           but composite phi does.
```

I interpret the doc to mean the regularization factor should be 3.72894e+10 in this case, but I don't see that in the .rec output. I see composite, measured, and actual phis are all equal.

I assume the "regularization" phi in the .rec output is the part that is "proportional to the inverse of the prior standard deviation of the respective parameter(s)" as mentioned in the doc. Which should then have another weight factor "uniformly applied to all parameter departures" to bring the "regularization objective function" up to _(reg_factor) * (current objective function)_.

So, how do I get the 10% penalty I deserve for my departing? Or am I misunderstanding?

**Comment by jtwhite79** [comment]
good question @wkitlasten .  The way ies_reg_factor is currently used is as a simple scaling factor against the current regularization objective function (not the measurement phi as it says in the manual). So in this case, an ies_reg_factor of 1.0 means use the full force of the regularization penalty (which is a function of the parameter deviations and the variance of the parameters - not related to measurement phi) where as ies_reg_factor if 0.1 says use 10% of the full regularization penalty.  I'll change the doc to make this clear.
