### ISSUE TITLE
issue with ++panther_transfer_on_finish/++panther_transfer_on_fail 

### ISSUE THREAD

**Issue by jesshe** [usgs/pestpp#206]
It seems file transfers using these control variables broke somewhere between the 5.1.6 and 5.1.21 releases

I was able to transfer files with the 5.1.6 release but it stopped working after replacing the executable with the 5.1.21 version (I was testing with the pestpp-ies windows exectuable)

Checking the .rmr after the failed file transfer, I got a funny printout saying -1 bytes were transferred upon closing the file despite previous printouts indicating the full filesize was transferred (copied the rmr output below).

Cheers!

_____________________________________________________________________________
PANTHER master listening on socket:0.0.0.0:4000 (IPv4)
running model 54 times
09/16/22 10:08:24->waiting for agents to appear

09/16/22 10:08:27->new connection from:HELLO:51373
09/16/22 10:08:27->initializing new agent connection from:HELLO$C:\test\Slave1 socket:HELLO:51373 number of agents:1
09/16/22 10:08:29->new agent ready:HELLO$C:\test\Slave1 socket:HELLO:51373
09/16/22 10:08:29->Sending run_id:0 to:HELLO$C:\test\Slave1 group_id:2  da_cycle:-9999   realization:1 concurrent:1)
09/16/22 10:08:45-> run_id:0 failed on agent:HELLO$C:\test\Slave1 group_id:2 group_id:2 run_id:0  da_cycle:-9999   realization:1  concurrent:1 worker_message:group_id:2 run_id:0  da_cycle:-9999   realization:1 
09/16/22 10:08:45-> agent:HELLO$C:\test\Slave1 request opened file:hostname=HELLO.agentdir=C--test-Slave1.runid=0.groupid=2.da_cycle:-9999.realization:1.run_status=failed.agent_filename=test.txt for file transfer of file:test.txt
09/16/22 10:08:45-> agent:HELLO$C:\test\Slave1 transferred bytes:5974 to file:hostname=HELLO.agentdir=C--test-Slave1.runid=0.groupid=2.da_cycle:-9999.realization:1.run_status=failed.agent_filename=test.txt
09/16/22 10:08:45->closed file:hostname=HELLO.agentdir=C--test-Slave1.runid=0.groupid=2.da_cycle:-9999.realization:1.run_status=failed.agent_filename=test.txt for file transfer of file:test.txt from HELLO$C:\test\Slave1 transferred bytes:-1
09/16/22 10:08:45->Sending run_id:1 to:HELLO$C:\test\Slave1 group_id:2  da_cycle:-9999   realization:3 concurrent:1)

**Comment by jtwhite79** [comment]
@jesshe I'll take a look at the file xfer stuff but there some tests covering that functionality.  Are you using the same machines and (trying to) transfer files with the same names?

**Comment by jesshe** [comment]
@jtwhite79 Thanks! Yeah I was running the manager and workers on the same machine. The files I was trying to transfer all have different names.

**Comment by jtwhite79** [comment]
OK.  Any chance you have to org use case and filenames laying around that you could test?  Just trying to eliminate problem sources....

**Comment by jesshe** [comment]
I've got my actual run going right now with v5.1.6 and the file xfer is working fine. Will try reproducing the error with the newer version and update once I get a chance.

**Comment by jesshe** [comment]
Okay, I swapped out the ies executable with the newest version (5.2.22), tried rerunning with otherwise the exact same setup and the file transfer failed with the same issue...

**Comment by jtwhite79** [comment]
Right on.  Can you post or message me the rmr files from 5.1.6 and 5.1.22.  I'll take a look...

**Comment by jtwhite79** [comment]
It looks like its something with the overly complex file names that are being formed in the master dir (at least for me) - windows can be picky about this. Probably will resort to a transfer record file and use generic names in the master dir...

**Comment by jtwhite79** [comment]
Turns out a colon was sneaking into the master dir file name and windows doesnt allow this.  So its been patched in 5.1.23 but eventually we will move to a more generic and general file transfer naming scheme.  Also just be careful - name of the file in the master dir cant be longer than 255 chars and they are getting pretty long already so if the path on the worker machine to the worker dirs is very long, you will run over 255.

**Comment by jesshe** [comment]
Many thanks! Yeah, gotta be careful to not bury the master in too many subdirectories right now so an eventual update to the naming scheme would be great
