### ISSUE TITLE
pestpp-pso and pestpp-sqp

### ISSUE THREAD

**Issue by BJEANNOT0** [usgs/pestpp#219]
Hello,

the user manual tells about pestpp-pso but it is not in the available downloads of the latest release.
Also, in the latest relase, there is a pestpp-sqp executable, but it is not discussed in the manual.

Could you please enlighten me about these two programs ?
Thank you for your help.
Best regards,

**Comment by jtwhite79** [comment]
pestpp-pso has been largely replaced with pestpp-mou as an evolutionary optimization tool for constrained single and multiple objective problems.  pestpp-sqp is (still) under active development but will (hopefully) be an industrial strength sequential quadratic programming tool for constrained optimization. Coming soon!

**Comment by BJEANNOT0** [comment]
Thank you !
Best regards,
