### ISSUE TITLE
Can I use PESTPP-MOU as a "more robust" alternative to PESTPP-IES ?

### ISSUE THREAD

**Issue by BJEANNOT0** [usgs/pestpp#220]
Hello,

I have a model I want to calibrate, whose response tends to be extremely non linear : that is, for some parameters, no response at all in the forecasts may be observed if the parameter stays under a given threshold.

In this framework, even if pestpp-ies is an ensemble method, I feel that because it is underpinned by a GLM framework, it might not be the best tool of the pestpp suite to deal with my problem.

To this regard, Pestpp-mou seems appealing at first glance. However, I do not want to perform optimization of management decision variables, but just parameter estimation and uncertainty quantification, just as in PESTPP-IES. Is it then appropriate for me to use PESTPP-MOU ?

Thanks in advance.
Best regards,

**Comment by jtwhite79** [comment]
This is a good question.  First of all, you are right to wonder about the ability of ensemble methods to deal with really nonlinear things.  Ive been using IES for a similar kind of problem I had to use a big ensemble (1,000 reals) with the multimodal upgrades using a really small local neighborhood (alpha = 0.05).  After about 10-20iters, it got to an nice place...but thats a lot of model runs...

You can def using MOU as a single obj optimizer - you just need to have one of the observations be the objective function (some measure of misfit to minimize).  So this could sum of squares or even some other metric of misfit (or even a few misfit metrics to use a multi objectives).  Just beware that MOU does not know anything about Bayes, so even tho it gives you a population, this is not a posterior ensemble and the best solution is not regularized (unless you also build in an objective for regularization to enforce the prior and then select a nice trade off solution)...also looking at a lot of model runs....

Hopefully your model runs fast!

**Comment by jtwhite79** [comment]
I should have also added that MOU will not scale to large numbers of parameters like IES.  Probably 200-250 npar tops for MOU...

**Comment by BJEANNOT0** [comment]
Thank you for your answer. I will try to use PESTPP-IES in a multimodal way. 
Best regards,
