### ISSUE TITLE
panther_transfer_on_finish/panther_transfer_on_fail with realization id

### ISSUE THREAD

**Issue by RyanConway91** [usgs/pestpp#230]
Possible future feature:
It seems like files transferred with panther_transfer_on_finish/panther_transfer_on_fail are simply given an id based on the order in which they are transferred. Information on the run id can be parsed from the .rmr file. However, it was an option to include the parameter realization id as well to avoid having to parse the rmr to find out the associated realization id for the file.

**Comment by jtwhite79** [comment]
The file names used to be redic long to the point that we were hitting os limits.  So we had to go with this more generic scheme.  Two points tho:  0) all the tools will transfer files so "realization number" might not exist and ii) pyemu can read the rmr file into a dataframe of Metadata columns...

**Comment by RyanConway91** [comment]
Great thanks, I'll use pyemu and the rmr then.

**Comment by hjia1005** [comment]
@jtwhite79  @RyanConway91  I am testing the panther_transfer_on_finish( ) option with pestpp-swp. I only used 5 realizations for a fast check. The files were transferred as expected. Also read the rmr file into a dataframe using Pyemu. My question is if the run_id is consistent with the realization id in the sweep_in.csv, such as the first parameter set has run_id 0 and the second has run_id 1, etc.

Thanks.

**Comment by hjia1005** [comment]
Checked again, and rmr file does have information on the realization id. Closed.
