### ISSUE TITLE
Divide %near bounds in 2 columns (%near_upbound and %near_lowbound)  ?

### ISSUE THREAD

**Issue by BJEANNOT0** [usgs/pestpp#247]
Hello,

in the process of finetuning the inversion process with pestpp-ies, i like to monitor the "%at/near bounds" data printed in the file case.rec, as they may be an indication that my bounds are not well defined (maybe I can lower the objective function a lot more if i extend just a little bit the bounds, while still preserving physically relevant parameter values).

In this process, my task would be greatly facilitated if the column "% at/near bnds" was divided into two columns : one for the upper bound and one for the lower bound. 

If you think this is a good idea, could you please study the possibility of implementing it in a next release of pestpp-ies ?
Thank you for your insights.

Best regards,

**Comment by jtwhite79** [comment]
Yeah that's a good idea...I'll add it to the next release

**Comment by jtwhite79** [comment]
implemented in latest release
