### ISSUE TITLE
5.2.4 pre-release encoding issue in tpl-built files

### ISSUE THREAD

**Issue by cnicol-gwlogic** [usgs/pestpp#254]
Hi Jeremy,

I think there might be an issue of some sort in the tpl routines of 5.2.4 pre-release. I haven't investigated deeply, but basically when pestpp (glm in this case) writes a file based on a template, I seem to get random encoding errors reported by python (pandas.read_csv() to be precise; example: "python UnicodeDecodeError: 'utf-8' codec can't decode byte XXXX in position XXXX invalid start byte"). 

That can be worked around by resetting the encoding on pd.read_csv() (eg encoding = 'unicode_escape'), but Pestpp 5.2.3 does not seem to suffer from this issue, so I've reverted to that - no big deal for me, but thought I'd let you know.  I am using windows machines, so this could be unique to that.

Cheers,

**Comment by jtwhite79** [comment]
Can you post the pst file (with offending par vals) and the tpl files so I can have a look?  Is this on windows?  Can you see anything weird in the tpl-created input files?

**Comment by cnicol-gwlogic** [comment]
@jtwhite79 - hold off, seems to be happening in 5.2.3 for me now too - probably something up at my end, as usual. But yep, windows PCs, and I see no difference even when doing a text compare between my originals and the tpl-created files (aside from precision).  

Will close this  once I work it out. Thanks.

**Comment by cnicol-gwlogic** [comment]
yep @jtwhite79 - my issue, not yours. Python didn't seem to like a set of characters I had in a table i was updating via a tpl file (a rogue "..." at the end of a long comment apparently - very weird. That same set of characters was in my original (hand made) table, but once updated via tpl, it shat the proverbial brick. I think we can ignore this is one a weird one-off issue, but feel free to re-open and I can send you files etc to replicate.

**Comment by jtwhite79** [comment]
Right on @cnicol-gwlogic keep me posted if there is anything I can do fix/check for additional issues...
