### ISSUE TITLE
virus?

### ISSUE THREAD

**Issue by volkerrath** [usgs/pestpp#27]
Hi, scanning with clamav I got the following message - probably a false positive, but better to alert:

/home/vrath/Github/pestpp/src/tests/run_manager_fortran_test/test_dir/pestpp_win.exe: Win.Ransomware.Sage-6995951-1 FOUND
/home/vrath/Github/pestpp/src/tests/runpy/yamr.dll: Win.Ransomware.Sage-6995951-1 FOUND

**Comment by jtwhite79** [comment]
Thanks for the heads up @volkerrath .  Im pretty sure there is no ransomware in pestpp!  I'll see if I can reach out to clamav to get some guidance on how to get this fixed.
