### ISSUE TITLE
pestpp-sen keywords 

### ISSUE THREAD

**Issue by laat0003** [usgs/pestpp#31]
Hi,

I'm using pestpp-sen to do gsa with an analytical element model but can't get the control variable keywords, as they are written in the manual (ver. 4.2.4) to be recognized. I wanted to use ++ method(sobol) but this ends up as an unrecognized keyword. I managed to guess at an alternative and got it to work with ++ gsa_method(sobol) but the same gsa_ prefix didn't work for the rest of the control keywords. I got the hint for the gsa prefix via the pestpp-sen usage examples that are displayed when you run pestpp-sen with no arguments. Can you please advise what the other control variable keywords are? Thanks in advance.

I'm using  ver. 4.2.16 compiled on 11 Oct 2019.

**Comment by jtwhite79** [comment]
I guess I’m not seeing this issue.  In the docx manual file in the documentation folder on the master branch, the section on pestpp-sen has tables for both Morris and Sobol input options.  They all start with ++gsa_ .  I think all the options are listed in those tables.  Let me know if I’m missing something.

**Comment by laat0003** [comment]
@jtwhite79  All fixed now. Thanks. The direct zip link now pulls the updated manual. Cheers for the rapid reply.
