### ISSUE TITLE
PARCHGLIM error with absolute(N) for a fixed value

### ISSUE THREAD

**Issue by mwtoews** [usgs/pestpp#4]
With PEST++ version 4.2.6, a new error is raised with a PEST control file that uses PARCHGLIM with absolute(N) inputs (e.g. see Table A1.8 from PEST user manual part 1). The error from `pestpp-ies` is:
 > parameter error: ROUGHCH01 'parchglim not in ['factor','relative']: ABSOLUTE(1)

In this particular case, PARTRANS is fixed, and the PEST user manual 1 states: "Note that If a parameter is tied or fixed, its change limit is ignored."

This particular control file worked with PEST++ 4.2.4, so it's a recent change. A suggested solution is to only permit (and ignore) absolute(N) if PARTRANS is fixed, as I guess was the behavior from previous versions. Implementing absolute(N) for non-fixed parameters seems like a bit of work, and should raise a parameter error for these combinations.

**Comment by jtwhite79** [comment]
That is a good point @mwtoews .  I'll add a check that only adjustable parameters are screened for parchglim compatibility
