### ISSUE TITLE
CMake build proposal

### ISSUE THREAD

**Issue by mwtoews** [usgs/pestpp#45]
The current build methods for PEST++ uses mixed methods based on either GNU Makefiles for Linux and macOS, or Visual Studio (I think?) for Windows. The Makefile setup that I redesigned (see [dwelter/pestpp#18](https://github.com/dwelter/pestpp/pull/18)) is fragile and difficult to maintain (I didn't know how to use CMake two years ago).

A proposed solution is to unify building with [CMake](https://cmake.org/), which is a popular cross-platform tool to build software on all of the operating systems with whatever compiler (e.g., GCC or Intel). [Modern CMake](https://cliutils.gitlab.io/modern-cmake/) methods are gaining traction on a wide range of C++ and/or Fortran projects because it is versatile, easier to use and manage. There are extra modules for testing and packing too (CTest and CPack).

So this is a proposal to add a CMake build setup for PEST++, which would essentially be a collection of `CMakeLists.txt` files in most directories, and some documentation. (Note that Eigen already has a CMake setup in this project, but it would be ignored, since Eigen is used as a header-only module.)

If this proposal sounds good, I can provide a PR for the develop branch. But I'm sure there are questions, so discuss any here.

**Comment by jwhite-usgs** [comment]
That would be awesome from my perspective @mwtoews !  Ive tried several times to learn cmake but was forced to turn back. @mnfienen-usgs - any concerns here?

**Comment by mwtoews** [comment]
Question time.

1. With version 5, will any Fortran source be retained for any purpose? Or will it be removed entirely? It's possible to configure a build with optional Fortran support. This would result with (e.g.) building mio, propack, rm_wrappers, pestpp-pso and inschekpp. But the default would only assume C++11 is available, and only C++ targets would be built.
2. Is MKL actually used? Or just standard math libraries with BLAS/LAPACK?
3. How important are building static vs shard libraries? This feature is well supported throughout CMake, controlled with a global [`BUILD_SHARED_LIBS`](https://cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html) variable. Should there be a default for each OS, or one default for all?
4. Is the default install directory still the custom source tree for PEST++: ./bin/{iwin,linux,mac,win}? Or should the default be the standard install prefix? (e.g. `/usr/local` or `C:\Program Files`)

**Comment by jtwhite79** [comment]
1) I think pestpp-pso and rm_wrappers will be retained.  Currently, they are optionally built (not by default).  Is this easily to configure?  With gcc I guess it’s not a problem to have gfortran, but on windows it usually means buying ifort. 
2) no mkl or blas/lapack - we are just relying on Eigen for linalg, except if pestpp-pso is being built, in which case we need access to lapack svd.  Maybe we could just hack in the svd routines into the pso source to avoid this dependency?
3) this one is tricky.  Even tho you can request a “static” build on Linux, the concurrency in c++11 needs the system-level shared libs so it’s not truely static - been burned by this.  But on windows and Mac, it can be.  Is there a way to trap for requesting static on Linux?
4) I guess I prefer prefer the same custom install dir just because that is where all the tests are looking, but I could be convinced otherwise...

**Comment by mwtoews** [comment]
1. Yup, it's not too difficult to configure optional Fortran support to compile pestpp-pso, and it's off by default. I suppose mio and propack will be dumped, since they are no longer linked to anything?
2. Perfect. But it looks like BLAS/LAPACK is required for Fortran support, in parsubs.f90, so this will be linked in if Fortran support is requested.
3. It turns out building static is simpler anyways, so I'll make this default. Shared building is difficult (but supported), as there is a cyclic dependency between pestpp_com and rm_abstract. It seems that the static linux binaries are not truly static, as they depend on common linux libraries. Some folks use Centos 5 or 6 to compile on so they can run on most other systems, such as ubuntu.
4. That's fine for now.

A PR is not too far off. It needs a bit of testing on Windows.

**Comment by mnfienen-usgs** [comment]
Hey @mwtoews - thanks for the work on this! I tried to run cmake on Centos 7 but ran into problems. 

I installed cmake 3.12.3. Then made a clean `build` dir under `src`. 

Tried running `cmake -DCMAKE_BUILD_TYPE=Release ..` and got the following output:

```- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at programs/gsa/CMakeLists.txt:20 (install):
  install TARGETS given no RUNTIME DESTINATION for executable target
  "pestpp-sen".


CMake Error at programs/pest++/CMakeLists.txt:13 (install):
  install TARGETS given no RUNTIME DESTINATION for executable target
  "pestpp-glm".


CMake Error at programs/pestpp-ies/CMakeLists.txt:12 (install):
  install TARGETS given no RUNTIME DESTINATION for executable target
  "pestpp-ies".


CMake Error at programs/pestpp-opt/CMakeLists.txt:14 (install):
  install TARGETS given no RUNTIME DESTINATION for executable target
  "pestpp-opt".


CMake Error at programs/sweep/CMakeLists.txt:12 (install):
  install TARGETS given no RUNTIME DESTINATION for executable target
  "pestpp-swp".


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.12)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
```

In full disclosure, I have absolutely no idea how to operate `cmake` so apologize if there is an obvious answer. Nonetheless, keen on any ideas you have.

**Comment by mwtoews** [comment]
@mnfienen-usgs right, I think I see what's happening there (also I didn't know cmake until a few years ago, so I would have been just as lost too). I believe you are in pestpp/src/build (i.e. in a build folder from src), and not pestpp/build (i.e. in a build folder from the base directory). Try again from a fresh build directory above the base directory, and make sure there aren't any other files/folders named cmake_install.cmake, CMakeCache.txt, or CMakeFiles/, as these may interfere.

**Comment by jtwhite79** [comment]
@mwtoews - this is working great so far - thanks again!  Is it possible to do the equivalent of a `-j5` for the iwin and win builds?

**Comment by mwtoews** [comment]
@jtwhite79 yes, parallel is certainly possible, but it depends on the generator and version of things you are using. The easiest for Windows is the use Ninja, either from their website or pip. If you plan to use Ninja with Fortran, then you should get the exe from Kitware ([here](https://github.com/Kitware/ninja/releases)). The Visual Studio generators can also do parallel too, but only with CMake 1.12 or later. I've expanded the documentation a bit more in #53 that will hopefully help.

I'm still finding the whole `./bin/{iwin,linux,mac,win}` directory a bit awkward. Normally, you'd expect binaries under `bin`, and not folders. Furthermore, these binaries quickly bulk up the repo size, for instance jtwhite79/pestpp is at least 2.97 GB, whereas pandas is only 125 MB. One idea to move binaries out of this repo is to upload the packaged binaries from `cpack -G ZIP` to tagged releases in https://github.com/usgs/pestpp/releases (this is what other projects do). It's a bit more overhead, but there are probably some helper scripts out there to streamline the process, both to upload and download to client machines.

**Comment by jtwhite79** [comment]
@mwtoews  - I agree that the `bin` dir with subdirectories is awkward and I think moving to releases would be very nice - something good to target for v5.  If we do drop the `bin\{}` dir, we will also need to rework the CI testing since it is expecting those platform-specific subdirs.  @mnfienen-usgs - is this all good with you?

**Comment by mnfienen-usgs** [comment]
hey @mwtoews - sorry late to get back to this, but you were right about the folder location. I tried again putting the build folder at the same level as `src` etc. and all worked fine. Thanks for sorting that out!

As for the `bin` dir issue, I'm cool with having tagged releases to avoid bloat. I think most people who use the tools will encounter the binaries through such a download rather than cloning/building/etc.

**Comment by mwtoews** [comment]
How about I amend #53 to create symbolic links for CI testing? This way either `./bin` and `./bin/linux` or `.\bin` and `.\bin\win` would be the same directory. The win/iwin/mac/linux tag can live with tagged releases.

**Comment by jtwhite79** [comment]
That will help with CI for sure.  But id still like to be able to specify a cmake_install_prefix to get the bins into the org dirs just until all this settles a little bit - it seems like “bin” is getting appended to whatever cmake_install_prefix is specified.  Can that be rolled back?

**Comment by mwtoews** [comment]
Or a better idea: automatically install the binaries in bin after they have been compiled, without needing further commands. This is generally not too difficult to do (based on [this](https://www.linux.com/training-tutorials/cmake-recipe-2-install-local-folder-build-dir-testing/)). The difficult hacky thing is to put them in a sub-directory within bin. I've added the symlinks for this command, so it should happen on all client machines after building (not just CI). When things are looking smoother, it would be nice to remove this hack and get the tests to look for the executables in ./bin only.

Also, the reason why I'd rather leave CMAKE_INSTALL_PREFIX / CMAKE_INSTALL_BINDIR alone is that these variables affects how CPack and "make install" work, and I can't find any easy way to allow these variables to also be used for local installs. Besides, it's much easier to automatically install them after they are built anyways.

**Comment by jtwhite79** [comment]
@mwtoews  - It looks like the windows intel C++ builds are not using the intel C++ compile (at least not for everything). Using either ninja or nmake, the resulting binaries still need the MSVC runtime dll that corresponds to the VS platform tool set - this is a problem for using the binaries on windows systems that have an older runtime (you can test this by taking the binaries to a windows machine that doesnt have VS installed):
<img width="480" alt="image" src="https://user-images.githubusercontent.com/1770912/80982233-47844000-8de8-11ea-932d-5360ebec192a.png">

However, if you use the pestpp_intel.sln to build the "i" prefixed binaries, these dont need the MSVC runtime - they are built entirely with the intel C++ compiler.  So does this mean the CMake build is maybe relying on the MSVC compiler for a portion of the build still?

**Comment by cnicol-gwlogic** [comment]
I ran into this issue the other day too - I found that if I used the "win"
binaries instead of the "iwin" ones, the issue was resolved. So I wondered
if there was something in the cake setup that was accidentally switched
around the wrong way. I haven't yet had a chance to dig around to look into
this yet sorry.

**Comment by jtwhite79** [comment]
@mwtoews I've dug into this a bit more.  Using dumpbin, I can see that using `cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=icl ..` followed by `ninja` results in a lot of  MSVCP140.dll and api-ms-win-***.dll deps, while building with pestpp_intel.sln doesnt have any, so it looks like the intel C++ compiler is not getting used?  Also, is the runtime library being set to `MT` or `MD`?

**Comment by mwtoews** [comment]
Thanks all for the report, and yes I know how to fix this one. The .sln/.vcxproj files all show `<RuntimeLibrary>MultiThreaded</RuntimeLibrary>` (or `MultiThreadedDebug`), which needs to be implemented for the CMake solution. Looking from `ninja -v`, it shows a different default MultiThreadedDLL (`/MD`). This is either handled using a really new feature from CMake 1.15 ([documented here](https://cmake.org/cmake/help/git-master/prop_tgt/MSVC_RUNTIME_LIBRARY.html)), however this is possibly too new, so I can hard-code the CXX flag ([something like this](https://stackoverflow.com/q/10113017)). I also want to modify some Linux settings to use [`-fvisibility=hidden`](https://gcc.gnu.org/wiki/Visibility) too, so I'll combine these in a PR that I'm preparing.

**Comment by mwtoews** [comment]
This should be resolved by #58, but I haven't done much testing with it to verify it.

Also, you can inspect Windows dependencies with `dumpbin /dependents ..\bin\pestpp-ies.exe`, which previously showed "VCRUNTIME140.dll" (i.e. the thing that caused the error), but now are fully static. (And `dumpbin` is available in a MSVC / Intel command prompt).

**Comment by jtwhite79** [comment]
@mwtoews - this is the gift that keeps on giving (I really appreciate your efforts!).  So that last pull request did seem to clear up the runtime dll, but Ive found another issue - for large-ish problems in terms of pars and obs, the CMake-ninja builds from windows error out with "bad allocation" (usually bc c++ cant reserve enough contiguous memory) but the builds from visual studio (MSVC or Intel) on the same problem/same machine do not error out with bad allocation and there is lots of memory avail (not sure if its contiguous...).  Is this possibly related to optimization flags or other compiler/link flags?

**Comment by mwtoews** [comment]
Try opening a basic command prompt (and not a developer prompt), and do this:
```
call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
```
and then create an empty build directory and run `cmake -GNinja ...`
Near the top of the configuration it should show the same compiler as the VS generator:
```
-- The CXX compiler identification is MSVC 19.24.28319.0
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe -- works
```

**Comment by jtwhite79** [comment]
From a standard prompt after calling vcvars:

From the `cmake -GNinja` generator:
```Configuring CMake 3.17.1 to build PESTPP 4.3.13
-- The CXX compiler identification is MSVC 19.22.27905.0
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.22.27905/bin/Hostx64/x64/cl.exe
```
From the `cmake -G"Visual Studio 16 2019" -A x64 ..` generator:

```
-- Configuring CMake 3.17.1 to build PESTPP 4.3.13
-- The CXX compiler identification is MSVC 19.22.27905.0
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.22.27905/bin/Hostx64/x64/cl.exe
```

**Comment by mwtoews** [comment]
And is the Ninja build still faulty for large numbers of pars/obs?

To take a look at the build commands you can enable verbosity, which is slightly different between the two generators (shown below). Make two build directories `build_vs2019` and `build_ninja`. Configure and build each project:
```
mkdir build_vs2019 && cd build_vs2019
cmake -G"Visual Studio 16 2019" -A x64 ..
cmake --build . --config Release
del src\programs\pestpp-ies\pestpp-ies.dir\Release\pestpp-ies.obj
cmake --build . --config Release -- /verbosity:normal
```
and the Ninja build:
```
call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
mkdir build_ninja && cd build_ninja
cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
ninja
del src\programs\pestpp-ies\CMakeFiles\pestpp-ies.dir\pestpp-ies.cpp.obj
ninja -v
```
in these examples, I'm just removing `pestpp-ies.obj` so that only a few objects need to be re-build with verbosity shown, otherwise there is too much to comb thru.

**Comment by jtwhite79** [comment]
Actually, the build from the clean prompt with vcvars set seems to be working for the MSVC compiler.  What’s up with that?

**Comment by mwtoews** [comment]
That's good information. How did you initially use Ninja, was it a developer prompt? And if so, what was the CXX compiler identification and path shown after the first cmake call?

You can also use `where cl` to see if some other compiler is on the PATH. All that I can say is that Ninja set's it's CXX compiler from what it sees on the PATH, whereas the Visual Studio generator uses a combination of either PATH and/or Windows Registry info (I think).

**Comment by jtwhite79** [comment]
I've been using it from the VS developer prompt (with Intel integration).  Here is the compiler info from that developer prompt

```
-- The CXX compiler identification is MSVC 19.22.27905.0
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.22.27905/bin/Hostx86/x86/cl.exe
``` 
Same as far as I can tell.  Maybe its the Intel integration?

**Comment by mwtoews** [comment]
I'm no MS dev pro, but I think `bin/Hostx86/x86/cl.exe` means that it's a 32-bit compiler (running on a 32-bit host?) PR #59 shows a warning message if this is attempted, because everyone should be using 64-bits to allocate more than [2 GB](https://en.wikipedia.org/wiki/2_GB_limit).

**Comment by jtwhite79** [comment]
That's interesting - I think you are right that the 32-bit compiler if being called but I've verified that the OS is x64.  So from the dev prompt, ninja is defaulting to x86.

**Comment by mwtoews** [comment]
does this prompt also show "x86" when you type `where cl`? Because I thought ninja took it's CXX from what it could see from the PATH, but perhaps I'm wrong about that.

**Comment by jtwhite79** [comment]
the developer prompt `where cl` is pointing to x86 - not sure why its defaulting to that.  But I'll just stay away from it

**Comment by jwhite-usgs** [comment]
Hey @mwtoews - @mnfienen-usgs and I just discovered that the Mac builds with cmake aren’t portable but using the old make scheme they are (using Mac intel compilers) - using cmake binaries on a Mac without intel compilers gets you a segfault in the parallel run mgr, which I think means pthreads isn’t being dynamically/statically linked correctly?  Any ideas on this?

**Comment by mwtoews** [comment]
@jwhite-usgs there are a few things to try, which I can't do as I don't have a mac intel compiler. You can inspect the executable with (e.g.) `otool -L pestpp-ies` to see what it links to. If it links to pthread from a system level, then that should be fine, but if it links to an intel library, then that's bad and non-portable.

First attempt is to try and ensure a system pthread is preferred:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index d73e6f8..71c6fb8 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -74,7 +74,10 @@ else()
   set(Fortran_ENABLED FALSE)
 endif()
 
+set(CMAKE_THREAD_PREFER_PTHREAD TRUE)
+set(THREADS_PREFER_PTHREAD_FLAG TRUE)
 find_package(Threads REQUIRED)
+message(STATUS "CMAKE_THREAD_LIBS_INIT=${CMAKE_THREAD_LIBS_INIT}")
 
 # Ensure C++11 is used
 set(CMAKE_CXX_STANDARD 11)
```
I have a second idea if this doesn't work.

**Comment by briochh** [comment]
Hi All, 

I've managed successful builds on Mac using my default (I think) C++ compiler `AppleClang 11.0.0.11000033` and following @mwtoews instructions for cmake in [here](https://github.com/usgs/pestpp/blob/master/documentation/cmake.md). Haven't checked the portability but the build process is straightforward enough. However, not sure if the C++ compiler is only an Xcode addition - so may not be on all Mac systems.
