### ISSUE TITLE
Tagged release proposal

### ISSUE THREAD

**Issue by mwtoews** [usgs/pestpp#55]
As mentioned in #45 it would be a good idea to move compiled executables out of the source tree, and into tagged releases. Binary archives are now easy to create with CPack ("free" from CMake setup), then each OS archive file is simply added to a github tagged release. For example, [here is one](https://github.com/mwtoews/pestpp-usgs/releases/tag/4.3.11). Related repos like pyemu can benefit from these, as it can also remove some of the binaries out (i.e. pyemu/bin), as this can be fetched from the github tagged release.

A simple script to quickly download and install the latest pestpp executables from github tagged releases (using the example linked above) is straight-forward, for example see [get_pestpp_bin.py](https://gist.github.com/mwtoews/4f7ae41f455da6d6ec25f342bb69082a), which is something that could be put in pyemu/scripts (but not yet).

**Comment by jtwhite79** [comment]
I like the idea of releases, but I need to understand how tagging and making releases on `develop` are transferred to `master` from what Ive read, it sounds like you have to manually remove releases and remake them, you can't change the branch of a release.  Can you verify that @mwtoews ?

**Comment by mwtoews** [comment]
The tagged release screen looks like this:
![Screenshot from 2020-04-22 10-06-50](https://user-images.githubusercontent.com/895458/79918728-1e2af200-8481-11ea-8a53-9091e6ef06da.png)

By default it looks for tags from "master", but you can get tags from any other branch, and you can make it a pre-release, which prevents it from being called "latest". You can always edit each release to toggle the pre-release button. I don't think releases actually get transferred between branches, since I think they reference a tag (which often are in multiple branches). However, it's probably worth testing in a forked repo (like mine).

So for the "develop" and "master" branches in this repo, I'd image that you could make pre-releases from the "develop" branch, and if/when they get merged to "master", then edit the release to toggle the pre-release button. (Most projects just have one "master" branch for leading development, so it's difficult to say if this would work for this case.)

**Comment by jtwhite79** [comment]
alright - sounds promising.  Lemme investigate...

**Comment by mwtoews** [comment]
Hey @jtwhite79, https://github.com/usgs/pestpp/releases/tag/4.3.11 looks pretty good so far. You could also repeat the tag in the "Release title", otherwise it shows the commit message "Merge pull request ...".

Also, I made a few arbitrary decisions while creating the CPack set-up that could potentially be refined. Respond to any of these as you feel fit:

1. The default CPACK_INCLUDE_TOPLEVEL_DIRECTORY was changed to OFF, which means the zip/tar.gz files don't contain a top-level directory. I probably changed this for convenience, but most archive formats use this feature, so they don't spill out a bunch of files in the directory.
2. Currently the only files packaged are under bin (the executables). Are there any other files that should be archived/distributed? Perhaps README.md and/or USGS_disclaimer.txt? Anything else?
3. Some CPack generator defaults can be baked-in, so you can type `cpack` to generate the desired format(s). Does ZIP for Windows and TGZ (.tar.gz) for Linux/mac sound good? (BTW, .tar.gz is preferred for Linux/mac to properly preserve the executable permission bit).

**Comment by jtwhite79** [comment]
Thanks @mwtoews - Im stumbling along here.  I think the way the cpack stuff works currently is fine - I added a batch and shell script to the repo so I can not remember all the steps for win and mac.  I wish there was a way to make the linux binaries static (not dependent on any system level dynamic links) but I havent found a way.

**Comment by mwtoews** [comment]
I can't say I know much about it, but I've seen projects like https://phusion.github.io/holy-build-box/ to try to make linux binaries as portable as possible. And for Cython projects, https://github.com/pypa/manylinux is used to upload binary wheels to PyPI, which is a system based on older CentOS versions.

You can see the symbol dependencies with ldd, e.g.:
```
$ ldd pestpp-ies 
	linux-vdso.so.1 (0x00007fff8bcc4000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5362526000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5362143000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5361da5000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5361b8d000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f536179c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5362c87000)
```
where the symbols on the left are required, and the symbols on the right are the ones that were found on the target system, which could be on different paths. These are found at runtime.

**Comment by mwtoews** [comment]
Further on Linux binaries, I had a look at Holy Build Box, and the results look promising. The results work on a few x64 linux machines I have access too. Also, this can be built on any computer that runs Docker (e.g. macOS). Interested in a PR with the build script?

**Comment by jtwhite79** [comment]
Hey @mwtoews - this does sound promising I would def be interested in seeing how it works.  Can we keep it optional or does it integrate into the cmake process?

**Comment by mwtoews** [comment]
It's just another build script that you can call from a console where docker is available, and the result is a "linux.tar.gz" file. See #62.
