### ISSUE TITLE
Pestpp-opt bounds enforcement

### ISSUE THREAD

**Issue by laat0003** [usgs/pestpp#64]
Hi,

Is there an option to have stricter bounds enforcement on decision variables when using -opt. I have a lower bound of 0.0 for injection rate on wells but I'm getting a really small negative number (-2.802e-045) fed into the template file. If the number is slightly larger (-1.262e-029) coming out of the SLP iteration then it does not go to the template file. I know that a rate that small will have no impact on model fluxes but unfortunately exponents that size in an input file trigger model run failure killing the optimization.  

I am using version 4.2.16 compiled October 11 2019.

**Comment by jtwhite79** [comment]
unfortunately, PESTPP-OPT was not strictly enforcing bounds (or checking for underflow) in the optimal decision variables coming out of the coin-or SLP solve - I can see where this could be a problem.  Ive just added checks for and enforcement of (slight) bound violation and also flushing underflow to zero - this fix will be available on the develop branch in release 4.3.14 once it tests out and gets merged.

**Comment by laat0003** [comment]
Cheers for the rapid reply. Much appreciated.
Tariq.
