### ISSUE TITLE
OPT behavior with chance constraints

### ISSUE THREAD

**Issue by laat0003** [usgs/pestpp#66]
Hi,

I am using PESTPP-OPT and am puzzled by what it does when using chance constraints. My simulations never complete a second iteration of optimization but it gets through the first iteration fine. It builds the response matrix for the second iteration then it just stops at the "calculating FOSM-based chance constraint components" stage, sends out an error to the workers and says simulation complete. I believe it may be related to the information written to the coin-log (attached) but I'll admit to being at a loss as to its meaning. I always test feasibility on the initial response matrix to make sure I select a chance constraint that is supposed to be calculable. I then use the base_jacobian() and hotstart_resfile() options to continue the optimization after selecting a feasible chance constraint. I've attached the coin-log, recfile and control file if they are of any help.
The error that appears on the worker cmd windows is as follows:

NetPackage::recv error - message did not originate from a PEST++ application
received corrupt message from to master: DESKTOP-PQON48A.hub:4004
error receiving message from master, terminating
error closing socket: (tcp/ip error id = 0) An operation was attempted on something that is not a socket. 

I don't get the error if I use risk neutral constraint and zero the weights on the calibration observations. Then the model proceeds for 15+ optimization iterations without a problem. I am running on a home cluster and have tried different machines to host the run manager. I am using version 4.2.16

[opt_controlfile.txt](https://github.com/usgs/pestpp/files/4723190/opt_controlfile.txt)
[opt_coinlog.txt](https://github.com/usgs/pestpp/files/4723191/opt_coinlog.txt)
[opt_recfile.txt](https://github.com/usgs/pestpp/files/4723088/opt_recfile.txt)

**Comment by jwhite-usgs** [comment]
Sorry you are having trouble.  Can you try the develop branch 4.3.14 release [https://github.com/usgs/pestpp/releases/tag/4.3.14](https://github.com/usgs/pestpp/releases/tag/4.3.14) to see if you get the same behavior?  There's been some work on the run mgr and a lot of work on the chance constraints lately that are only the develop branch (these changes will soon be merged into master and will be version 5).  If the problem persists, can you upload your files so I can debug?

**Comment by laat0003** [comment]
Cheers for the quick response.
I compiled the develop branch using the batch script and performed a run with the executable.
 Good news and bad news. 
Good news: It now moves forward with the optimisation using the chance constraints as expected. Awesome!

Bad news
The run manager doesn't like me using a VNC service. It seems to corrupt the security packages that are sent to the workers saying they are empty. No big deal though, I just shut down the vnc server and all workers ran fine until ....
they have to remain idle while waiting for the rest of the runs to finish for the response matrix.  Unless they immediately receive a parameter set, they terminate with: "no ping received from master in the last 300 seconds, terminating"
Just to be clear, they are not idle before terminating. They send results, send ready signal, then terminate unless a parameter set is still waiting to be run.
If I restart the workers then they will happily sit idle until fed a parameter set so the issue is limited to workers who have already run models and need to remain idle for a period until the manager sends new parameter sets.

**Comment by jtwhite79** [comment]
Thanks for the feedback. I’m glad opt is doing better.  Also that’s actually really good news about the vlc issue(s).  I’ve been seeing those issues intermittently and could not reproduce.  So now maybe there is a way to force it to happen consistently.

**Comment by laat0003** [comment]
No problem. Any suggestion for a workaround to keep the workers alive while they wait for the others to catchup? Aside from manually checking each one and restarting.

**Comment by jtwhite79** [comment]
There is an option to control the length of time between pings that the agents will tolerate  - panther_agent_no_ping_timeout_secs.  It’s set to 300 seconds, maybe try a bigger number?  But it seems like something maybe up since the master should ping much more frequently than that.  Lemme know if increasing that number helps.

**Comment by laat0003** [comment]
Happy to close this since there is a workaround and changes are in effect unless the dev team feels otherwise.

**Comment by cnicol-gwlogic** [comment]
> No problem. Any suggestion for a workaround to keep the workers alive while they wait for the others to catchup? Aside from manually checking each one and restarting.

You could try use the option ++panther_agent_restart_on_error(true) - I actually thought this was the default behaviour (since roughly 4.3.13 I think), but maybe not by the sound of your experience.

**Comment by jtwhite79** [comment]
@cnicol-gwlogic I think that is the default and it works well!   But the agent no ping timeout was tripping the agents to shutdown regardless of the restart flag.  So I changed the no ping timeout to be off by default.  That ok with you?

**Comment by cnicol-gwlogic** [comment]
@jtwhite79 - no worries, sounds good to me and thanks for finding a solution - was getting worried I had really fired something. 

> @cnicol-gwlogic I think that is the default and it works well! But the agent no ping timeout was tripping the agents to shutdown regardless of the restart flag. So I changed the no ping timeout to be off by default. That ok with you?
