### ISSUE TITLE
losing agents on linux

### ISSUE THREAD

**Issue by mnfienen-usgs** [usgs/pestpp#67]
building on issue #66 from @laat0003. 

I am getting similar timeouts and losing agents when they are idle with the message of `no ping received from master in the last 300 seconds, terminating` in output on agent side.

Setting `++panther_agent_no_ping_timeout_secs(1000000)` seems to stop it.

**Comment by laat0003** [comment]
I didn't push my timeout that high and still had issues but will give this a try. 
@mnfienen-usgs many thanks for the information.

**Comment by jwhite-usgs** [comment]
The agent timeout is now disable by default, so hopefully this is no longer a problem.  Please reopen if the issue persists.
