### ISSUE TITLE
Couple of seq DA queries

### ISSUE THREAD

**Issue by MJKnowling** [usgs/pestpp#68]
In addition to my PR on your fork @aymanalz

@jtwhite @aymanalz  It is going to be a common case that we have many cycles (e.g., daily models), many of which will not contain any data to assimilate! I think we can just bypass the `kf_update()` in the case of seq DA or `iterate_2_solution()` in the case of IES near line 533 of `pestpp-da.cpp` after doing the "forecast" EnKF step (using an appropriate condition related to the number of "active" (i.e., current cycle) non-zero weighted obs). Thoughts? Want me to go ahead with this? 

Also @ayman, are you able to run your `da_pumping_test_enkf` test through? I get termination in the initialization of the second cycle.

More to come!

**Comment by jtwhite79** [comment]
@MJKnowling I agree we should support “no analysis” cycles and in fact, even an entire run with no analysis, where we simply propagate forward the forecast states thru the cycles - I guess this is equivalent to a prior Monte Carlo.

**Comment by MJKnowling** [comment]
Great idea! I will try to hack that in too if you’re happy @aymanalz?
