### ISSUE TITLE
PESTPP-OPT risk neutral with base jco

### ISSUE THREAD

**Issue by laat0003** [usgs/pestpp#75]
Hi,

When doing a risk neutral optimization, model parameter sensitivity is excluded from the jco, which makes sense. However, if you then try to use the resultant jco via base jacobian() for another risk neutral optimization you cannot proceed unless you supply a jco that includes the adjustable model parameter sensitivities. Not exactly a deal breaker but just thought I'd flag it.  

I'm using version 4.3.17

**Comment by jwhite-usgs** [comment]
Thanks for the heads up - this should be fixed in 4.3.18.
