### ISSUE TITLE
PESTPP-SWP parsing problem -- returning error on !dum! observation

### ISSUE THREAD

**Issue by hwreeves-USGS** [usgs/pestpp#81]
I used !dum! to denote unneeded numbers in an instruction file to help parse the line and
find the observed value.  I can use the instruction file with a pest executable, but pestpp-swp is
returning an error:

checking model IO files... L1  !DUM!  !SUM_MASS5! !ES_TOTAL5! !ES_GLAC5! !ES_BDRX5! !PAL_TOTAL5! !PAL_GLAC5! !PAL_BDRX5! !ES_1MI5! ~%~ !ES_05MI5! ~%~ !PAL_1MI5! ~%~ !PAL_05MI5!
control file parsing error: error in model interface file checking: InstructionFile error in file AOC_obs.ins : observation 'DUM' listed multiple times in ins file 'AOC_obs.ins'
control file parsing error: error in model interface file checking: InstructionFile error in file AOC_obs.ins : observation 'DUM' listed multiple times in ins file 'AOC_obs.ins'
Error condition prevents further execution:

I'll note that I used lower case, !dum!, in the file as used in the documentation.

**Comment by jwhite-usgs** [comment]
@hwreeves-USGS - just checking that the latest binaries can deal with multiple "dum" entries in an instruction file?

**Comment by hwreeves-USGS** [comment]
Sorry Jeremy - yes, the latest version handles the !dum! entries on multiple lines.

HWR


Howard W. Reeves
Groundwater and Watershed Modeling Team Lead
USGS Upper Midwest Water Science Center
5840 Enterprise Drive
Lansing, Michigan 48911
517-887-8914
________________________________
