### ISSUE TITLE
Only active pars (nonzero wt obs) in localizer?

### ISSUE THREAD

**Issue by wkitlasten** [usgs/pestpp#96]
I am getting "the following cols were not found in the active par names..." error whenever I fix a few pars. If I recall, I get a similar error when I set some weights to 0. I can rebuild my localizer each time, no problem... but it might be more convenient (for people like me anyway!) if there was a warning about inactive pars and zero weight obs in the localizer, rather than a full stop. Or, is there a reason this might be undesirable?

**Comment by jtwhite79** [comment]
The localizer is strict about entries but it could be more forgiving.   Its just hard to deal with because we allow group names mixed with individual names. But I think we will need this for upcoming pestpp-da tool so I'll take a look.

**Comment by wkitlasten** [comment]
On a vaguely related note, any suggestions for speeding up the "initializing localizer" step? Mine is only 10105 x 17707, but it seems to take a long time to initialize.

**Comment by jtwhite79** [comment]
There might be some optimizations to be had in their.  I'll take a look.  Can send me your files?

**Comment by wkitlasten** [comment]
I'm sure there is! I converted it to .jcb format and it loads faster.
